Fix error when removing uploaded post breach file on config reset
guardicore/monkey pull request #1054
Opened 2021-03-25 14:37 UTC by shreyamalviya

Fixes:
![image](https://user-images.githubusercontent.com/44770317/112489824-d2757c80-8da4-11eb-9a68-c74357ca27d1.png)
`os.remove(file_path)` in `monkey_island/cc/resources/pba_file_upload.py` attempts to delete a directory which throws an error when the PBA_linux_filename/PBA_windows_filename field in the database is empty.
<img src="https://user-images.githubusercontent.com/44770317/112490402-5891c300-8da5-11eb-96f2-7b3b1c9aadbd.png" height=75>

2021-04-22 18:30 UTC, mssalvatore requested changes
It would be nice, but not mandatory, to add some tests for this function. I'm not sure how if pytest plays nicely with the `@jwt_required` decorator.

2021-04-22 18:30 UTC, mssalvatore commented on monkey/monkey_island/cc/resources/pba_file_upload.py
> +                ConfigService.set_config_value(filename_path, "")
Should the call to `ConfigService.set_config_value()` be done in a `finally` to ensure that it happens if `os.remove()` raises an exception?

2021-04-22 18:30 UTC, mssalvatore commented on monkey/monkey_island/cc/resources/pba_file_upload.py
> +                LOG.error("Can't remove previously uploaded post breach files: %s" % e)
What about something like:

```python
if filename:
   ConfigService.set_config_value(filename_path, "")
   FileUpload._delete_file(file_path)

...

@staticmethod
def _delete_file(file_path):
    try:
        if os.path.exists(file_path):
...
```

2021-04-24 08:13 UTC, shreyamalviya commented
@mssalvatore I'm not sure how much value we'll get out of adding tests for this.

2021-04-24 22:48 UTC, mssalvatore commented
> @mssalvatore I'm not sure how much value we'll get out of adding tests for this.

Had we had the tests in the first place, this bug might have been prevented. Where possible, we should try to first write a test that reproduces the issue, then fix it and see that the test passes. A set of tests for this function seems feasible. It's also a good opportunity to investigate the best way to test our API endpoints. 

![image](https://user-images.githubusercontent.com/19957806/115974835-a7aa4f80-a52d-11eb-8dd5-49b3f1c837c3.png)
https://flask.palletsprojects.com/en/1.1.x/testing/

2021-04-24 23:00 UTC, mssalvatore requested changes

2021-04-26 13:06 UTC, merged