Unit test files consistency
guardicore/monkey pull request #1094
Opened 2021-04-09 09:19 UTC by shreyamalviya

# What does this PR do? 

Fixes #925 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] ~Was the documentation framework updated to reflect the changes?~ NA

## Testing Checklist

* [ ] ~Added relevant unit tests?~ NA
* [x] Have you successfully tested your changes locally? Elaborate:
    - Existing unit tests pass 
* [ ] If applicable, add screenshots or log transcripts of the feature working

2021-04-12 11:25 UTC, mssalvatore requested changes

2021-04-13 06:24 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/test/monkey_test_endpoint.py
> +class MonkeyTestEndpoint(flask_restful.Resource):
Term `test` is still confusing. If possible, I'd rename the path to `monkey_island/cc/resources/blackbox/blackbox_monkey`. When you see the term blackbox it obvious what it means, meanwhile `test` doesn't tell a whole lot and also confuse you between unit test or different kind of test.

2021-04-13 06:26 UTC, VakarisZ requested changes
Would be ideal if you could fix the naming of blackbox resources by replacing word `test` with word `blackbox` where it makes sense. This includes the URI's of the resources

2021-04-14 08:21 UTC, VakarisZ commented on monkey/monkey_island/cc/app.py
> +from monkey_island.cc.resources.blackbox.telemetry_blackbox_endpoint import TelemetryTestEndpoint
Rename classes to match filenames

2021-04-14 08:23 UTC, VakarisZ requested changes
One small thing remaining: rename classes to match filenames. Class in `monkey_island.cc.resources.blackbox.log_blackbox_endpoint` should be named `LogBlackboxEndpoint`, not `LogTestEndpoint`

2021-04-14 12:49 UTC, mssalvatore approved these changes

2021-04-14 12:49 UTC, merged