Add API endpoint for ransomware report
guardicore/monkey pull request #1297
Opened 2021-07-05 11:00 UTC by shreyamalviya

# What does this PR do? 

#1240  

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing? 
* [x] ~Was the CHANGELOG.md updated to reflect the changes?~
* [x] ~Was the documentation framework updated to reflect the changes?~

## Testing Checklist

* [x] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Ran Island and added a log statement in `ReportPage.js` to make sure it worked.
* [x] ~If applicable, add screenshots or log transcripts of the feature working~

2021-07-05 12:33 UTC, mssalvatore requested changes
This should get a changelog entry, since it's changing Monkey Island's API.

2021-07-05 12:33 UTC, mssalvatore commented on monkey/monkey_island/cc/resources/ransomware_report.py
> +        return jsonify({"show": True, "report": None})
The back end should not be making decisions about what the front end should show. It's the backend's job to report what data it has. It's the frontend's job to decide how to display that data.

2021-07-06 08:40 UTC, ilija-lazoroski approved these changes

2021-07-06 13:20 UTC, mssalvatore approved these changes

2021-07-06 13:22 UTC, merged