Ransomware exploitation details report service
guardicore/monkey pull request #1306
Opened 2021-07-08 10:20 UTC by shreyamalviya

# What does this PR do? 

#1240 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [x] ~Was the CHANGELOG.md updated to reflect the changes?~
* [x] ~Was the documentation framework updated to reflect the changes?~

## Testing Checklist

* [x] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the Island and logging response from the API endpoint 
* [x] ~If applicable, add screenshots or log transcripts of the feature working~

2021-07-08 10:52 UTC, mssalvatore requested changes

2021-07-08 10:52 UTC, mssalvatore commented on monkey/monkey_island/cc/resources/ransomware_report.py
> +            {"report": None, "stats": RansomwareReportService.get_exploitation_details()}
```suggestion
            {"report": None, "propagation": RansomwareReportService.get_exploitation_details()}
```

2021-07-08 10:52 UTC, mssalvatore commented on monkey/monkey_island/cc/services/ransomware_report.py
> +
This code is unnecessary.

2021-07-08 10:52 UTC, mssalvatore commented on monkey/monkey_island/cc/services/ransomware_report.py
> +class RansomwareReportService:
I realize this is the pattern for the rest of the services, but a class that stores no state and only contains static methods doesn't make a whole lot of sense. The class doesn't serve any purpose. This pattern seems like something someone picked up from Java and carried over to Python.

We can just make `get_exploitation_details()` a function and call `ransomware_report.get_exploitation_details()`

2021-07-09 06:40 UTC, VakarisZ commented on monkey/monkey_island/cc/services/ransomware_report.py
> +    exploited = ReportService.get_exploited()
What exactly do we need for statistics? There's no need to send all exploited and especially scanned nodes. Maybe the count is enough?

2021-07-09 07:20 UTC, shreyamalviya commented on monkey/monkey_island/cc/services/ransomware_report.py
> +    exploited = ReportService.get_exploited()
Won't we need the details for the table (we need the machine, how it was exploited, and ransomware simulation details)?

2021-07-09 07:27 UTC, ilija-lazoroski approved these changes

2021-07-09 10:43 UTC, mssalvatore commented on monkey/monkey_island/cc/services/ransomware_report.py
> +    exploited = ReportService.get_exploited()
I think the front end does very little (if any) report processing. So we could do all of the processing on the back end and send just the information that will be displayed.

```python
{"numScanned":  len(scanned), "numExploited": len(exploited), "exploits" {"wmi": 7, "smb": 13 ... }}
```

2021-07-09 11:47 UTC, shreyamalviya commented on monkey/monkey_island/cc/services/ransomware_report.py
> +    exploited = ReportService.get_exploited()
So the ransomware report won't show the exploit that gave access successful to a particular machine?

2021-07-12 07:54 UTC, shreyamalviya commented on monkey/monkey_island/cc/services/ransomware_report.py
> +    exploited = ReportService.get_exploited()
Done
![image](https://user-images.githubusercontent.com/44770317/125250037-7282f180-e313-11eb-8821-041ea82e538c.png)

2021-07-12 11:02 UTC, mssalvatore requested changes

2021-07-12 11:02 UTC, mssalvatore commented on monkey/monkey_island/cc/services/ransomware_report.py
> +        "count_per_exploit": _get_exploit_counts(exploited),
It seems weird to have two of these named "num" and one named "count". "num" and "count" basically mean the same thing, and I don't think the distinction here is valuable for the consumer of the API.

I think "num_per_exploit", "num_hosts_per_exploit", or "num_nodes_per_exploit" would be better.

I'm also wondering if "hosts" would be better than "nodes", but I don't feel too strongly about this.

2021-07-12 17:38 UTC, merged