Ransomware encryption table data
guardicore/monkey pull request #1308
Opened 2021-07-09 08:38 UTC by VakarisZ

# What does this PR do? 

Fixes  part of #1240

Add any further explanations here. 

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by running manually
* [ ] If applicable, add screenshots or log transcripts of the feature working

2021-07-09 08:41 UTC, VakarisZ commented on monkey/tests/unit_tests/monkey_island/cc/services/ransomware/test_ransomware_report.py
> +    return mongo
I need help with this one. 
`RansomwareReportService` uses `ReportService` which further down the road uses `Monkey` model. I can't seem to find a way to force the model to use the same database as we use here.

2021-07-12 11:21 UTC, mssalvatore requested changes

2021-07-12 11:21 UTC, mssalvatore commented on monkey/tests/unit_tests/monkey_island/cc/services/ransomware/test_ransomware_report.py
> +@pytest.mark.skip(reason="Can't find a way to use the same mock database client in Monkey model")
This test is unconditionally skipped. It should either be run or removed.

2021-07-12 11:21 UTC, mssalvatore commented on monkey/monkey_island/cc/services/ransomware/ransomware_report.py
> +            }
This should have the number of successfully encrypted files, not just true or false. From the acceptance criteria:
![image](https://user-images.githubusercontent.com/19957806/125279107-87df2800-e2e1-11eb-96f9-6a96e92f9ec9.png)

2021-07-13 07:55 UTC, shreyamalviya commented on monkey/monkey_island/cc/services/ransomware/ransomware_report.py
> +    origin_exploits = [
Why call this _get_monkey_origin\_**exploits**? It's returning the origin of the monkey on a machine whether it was an exploit or manual execution.

2021-07-13 08:19 UTC, VakarisZ commented on monkey/monkey_island/cc/services/ransomware/ransomware_report.py
> +    origin_exploits = [
"Monkey origin" is too ambiguous, it could mean "where monkey got downloaded from", for example. "Exploit" indicates that it means which exploit got monkey into the system. "Manual run" is also an exploit in terms of a simulation. If you have a clearer name suggest and let's fix, I couldn't come up with one without being verbose

2021-07-13 10:46 UTC, mssalvatore approved these changes

2021-07-13 10:46 UTC, merged