Documentation for PowerShell exploiter
guardicore/monkey pull request #1427
Opened 2021-08-24 11:32 UTC by ilija-lazoroski

# What does this PR do? 

Fixes parts of #1246 . 

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...} 
* [ ] If applicable, add screenshots or log transcripts of the feature working

![image](https://user-images.githubusercontent.com/15820737/130607258-bd704a9b-a225-460c-97f4-2b588437ff27.png)
![image](https://user-images.githubusercontent.com/15820737/130607324-e9867971-a2c0-4ecf-bcad-4c3737060664.png)

2021-08-24 12:41 UTC, mssalvatore commented on envs/monkey_zoo/docs/fullDocs.md
> +[Nr. 27 Powershell](#_Toc536021480)<br>
These numbers match the last octet of each machine's IP address.

2021-08-25 06:21 UTC, shreyamalviya requested changes

2021-08-25 06:21 UTC, shreyamalviya commented on docs/content/reference/exploiters/powershell.md
> +(see ["configuration"]({{< ref "/usage/configuration" >}}) for instructions) .
Can we add some more information here? I don't love just having one sentence in the description where the user probably expects to get a fairly detailed explanation.

2021-08-30 08:32 UTC, shreyamalviya requested changes
There's a bunch of stuff we don't need. Let's simply make sure that we add the following information:
- some information about PowerShell Remoting
- the exploiter brute-forces with credentials configured or gathered
- mitigations, briefly; and that security concerns, recommendations, and best practices when using PowerShell Remoting can be found at https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/winrmsecurity?view=powershell-7.1

2021-08-30 08:32 UTC, shreyamalviya commented on docs/content/reference/exploiters/powershell.md
> +3. List of usernames and passwords as plain-text entered by the user.
All of this is just implementation details which, as a user, I don't care about. Mentioning brute-forcing is good enough, IMO.

2021-08-30 08:32 UTC, shreyamalviya commented on docs/content/reference/exploiters/powershell.md
> +Windows Remote Management(WinRM) services to propagate to a victim.
I'm not sure if this is 100% accurate. PSRP is a protocol and PowerShell Remoting is a method of controlling Windows systems. To say that this is an exploit that uses PSRP may suggest that we're exploiting the protocol, which is false.

Try something like this (this is not the best but all that I could come up with right now):
```suggestion
This exploiter uses brute-force to propagate to a victim through PowerShell Remoting using Windows Remote Management (WinRM).
```

2021-08-30 08:32 UTC, shreyamalviya commented on docs/content/reference/exploiters/powershell.md
> +More on [Windows Remote Management]("https://docs.microsoft.com/en-us/windows/win32/winrm/portal").
This is just details about PSRP and WinRM from the documentation. If someone wants to know about them in detail, they can look up the documentation themselves. We don't need to replicate the information in our documentation.

2021-08-30 11:18 UTC, VakarisZ commented on docs/content/reference/exploiters/powershell.md
> +Windows Remote Management(WinRM) services to propagate to a victim.
I don't think we need to be 100% accurate or precise. We're exploiting remote powershell setups, we don't need to elaborate on which protocols powershell remoting uses, right?

2021-08-30 11:24 UTC, shreyamalviya commented on docs/content/reference/exploiters/powershell.md
> +Windows Remote Management(WinRM) services to propagate to a victim.
Exactly, no need to mention PSRP at all.

2021-08-30 12:06 UTC, mssalvatore commented on docs/content/reference/exploiters/powershell.md
> +3. List of usernames and passwords as plain-text entered by the user.
I think this information is good, but the level of detail isn't right. What I mean is, it's good information that the exploiter attempts to use stored credentials and passwords. It's too low level to say "we set Password = None".

2021-08-31 16:21 UTC, mssalvatore approved these changes

2021-09-01 09:40 UTC, shreyamalviya approved these changes

2021-09-01 09:41 UTC, merged