Report encryption
guardicore/monkey pull request #1477
Opened 2021-09-21 08:01 UTC by VakarisZ

# What does this PR do? 

Addresses #1454

## PR Checklist
* [x] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Have you successfully tested your changes locally? Elaborate:
    > 
![image](https://user-images.githubusercontent.com/36815064/134134193-e9556148-cdbb-486a-84f0-9c17c80bdad7.png)

2021-09-21 13:53 UTC, VakarisZ commented on monkey/monkey_island/cc/services/reporting/report.py
> +        report = ReportService.encode_dot_char_before_mongo_insert(report)
Move to report model

2021-09-21 14:33 UTC, VakarisZ commented on monkey/monkey_island/cc/models/utils/report_encryptor.py
> +    field_type: Type[FieldTypeABC]
Consider renaming to `field_encryptor`

2021-09-21 14:39 UTC, VakarisZ commented on monkey/monkey_island/cc/server_utils/encryption/string_encryptor.py
> +def encrypt(cleartext: str) -> str:
Remove this layer

2021-09-21 14:48 UTC, mssalvatore requested changes

2021-09-21 14:50 UTC, VakarisZ commented on monkey/monkey_island/cc/models/utils/report_encryptor.py
> +sensitive_fields = [SensitiveField(path="overview.config_passwords", field_type=StringList)]
Another PR will generalize this file and move this line to report model

2021-09-21 17:59 UTC, mssalvatore commented on monkey/monkey_island/cc/models/utils/field_encryptors/string_list_encryptor.py
> +class StringListEncryptor(IFieldEncryptor):
Needs tests

2021-09-22 07:26 UTC, VakarisZ commented on monkey/monkey_island/cc/models/utils/field_encryptors/string_list_encryptor.py
> +class StringListEncryptor(IFieldEncryptor):
Added tests

2021-09-22 07:35 UTC, ilija-lazoroski approved these changes
Amazing work!

2021-09-22 08:48 UTC, merged