Delay mongo init to after registration
guardicore/monkey pull request #1495
Opened 2021-09-28 08:01 UTC by shreyamalviya

# What does this PR do? 

#1463 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing? 
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the Island (deleted data dir, deleted DB, deleted server config, deleted creds)
    > Tested by running Hugo.
* [x] If applicable, add screenshots or log transcripts of the feature working

![image](https://user-images.githubusercontent.com/44770317/135046686-17565583-4557-49cd-9710-9f65a4a9dd36.png)

2021-09-28 08:21 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/auth/auth.py
> +            _check_attack_mitigations_in_mongo()
This checks for attack mitigations during login? Why? Shouldn't it happen during registration?

2021-09-28 08:26 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/auth/auth.py
> +        init_collections()
I feel like this function doesn't belong here since it has nothing to do with authentication's resource

2021-09-28 08:35 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/auth/registration.py
> +            _drop_mongo_db()
All this logic should be moved into `init_collections` method which gets called during registration. This way interaction with mongodb during registration is separated from the logic of resources. In general resources shouldn't interact with database directly.

2021-09-28 08:38 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/auth/registration.py
> +            )
if the error has to do with interaction with mongo we should catch it when interacting with mongo.

2021-09-28 08:40 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/auth/registration.py
> +            return make_response({"error": str(ex)}, 400)
What's the poin of this response? user can already see the error in logs and we don't handle 400 in any special way on the front end.

2021-09-28 08:42 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/auth/registration.py
> +    mongo.db.command("dropDatabase")
why not `mongo.drop_database('db')`? Why are we even dropping the whole database if we're going to import the exact same mitigations?

2021-09-28 08:42 UTC, VakarisZ requested changes
Mostly nit-picking on the readability, but some major questions as well.

2021-09-29 13:45 UTC, VakarisZ approved these changes

2021-09-29 13:51 UTC, mssalvatore approved these changes

2021-09-29 13:51 UTC, mssalvatore commented on monkey/monkey_island/cc/setup/mongo/database_initializer.py
> +        logger.info("Populating Monkey Island with ATT&CK mitigations, this might take a while...")
This happens very quickly now (< 5ms). I think we can remove "this might take a while..."

2021-09-29 13:54 UTC, ilija-lazoroski approved these changes
Great job!

2021-09-29 14:03 UTC, merged