Modify "Communicate as Backdoor User" PBA's HTTP requests
guardicore/monkey pull request #1580
Opened 2021-11-11 14:00 UTC by shreyamalviya

# What does this PR do? 

Fixes #1577 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing? 
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [ ] ~Was the documentation framework updated to reflect the changes?~

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the modified commands manually. 
* [ ] ~If applicable, add screenshots or log transcripts of the feature working~

2021-11-11 14:23 UTC, mssalvatore requested changes
![image](https://user-images.githubusercontent.com/19957806/141314169-164f4d41-8e39-4184-814e-54aafc6d6c36.png)

We should test the agent to ensure everything actually works as expected.

2021-11-12 06:16 UTC, shreyamalviya commented
Tested agent from source, works

2021-11-12 09:05 UTC, ilija-lazoroski approved these changes

2021-11-12 12:56 UTC, mssalvatore approved these changes

2021-11-12 12:56 UTC, merged