Remove max iterations and timeout between iterations options
guardicore/monkey pull request #1600
Opened 2021-11-16 07:31 UTC by shreyamalviya

# What does this PR do? 

Fixes #1537  

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...} 
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

2021-11-16 12:11 UTC, mssalvatore commented
I think we can also get rid of "retry failed exploitation." If I understand it correctly, that option allows you to enable or disable whether or not the monkey will retry exploitation in subsequent runs. Since there's now only 1 run, the option is meaningless. Please inspect the code to confirm.

2021-11-16 13:18 UTC, ilija-lazoroski approved these changes
Looks good to me.

2021-11-18 06:58 UTC, shreyamalviya commented
![image](https://user-images.githubusercontent.com/44770317/142367417-b58edee1-6c6d-462d-a2ab-27189baa9017.png)

2021-11-18 09:47 UTC, ilija-lazoroski requested changes
Travis is failing due to swimm unit `Add a new configuration to the Agent` . I am guessing the problems are first line numbers. 
![image](https://user-images.githubusercontent.com/15820737/142391377-ee135a36-a567-4d36-b650-636f8a5fe820.png)
![image](https://user-images.githubusercontent.com/15820737/142391418-abd3333b-594c-41b4-885a-024371d8b2c8.png)

2021-11-18 13:25 UTC, mssalvatore approved these changes

2021-11-19 13:08 UTC, merged