1605 pass wormconfig options
guardicore/monkey pull request #1724
Opened 2022-02-18 19:09 UTC by ilija-lazoroski

# What does this PR do? 

Fixes #1605 . 

Add any further explanations here. 

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...} 
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

2022-02-20 19:31 UTC, mssalvatore requested changes

2022-02-21 11:20 UTC, VakarisZ approved these changes

2022-02-21 12:06 UTC, shreyamalviya commented on monkey/infection_monkey/master/exploiter.py
> +        exploiters_to_run = list(deepcopy(ordered_exploiters))
Why do we need to convert an iterable to a list? As far as I can tell, we should be able to use it as it is.

2022-02-21 12:10 UTC, shreyamalviya commented on monkey/infection_monkey/master/exploiter.py
> +            f"{','.join([e['name'] for e in exploiters_to_run])}"
```suggestion
            f"{', '.join([e['name'] for e in exploiters_to_run])}"
```

2022-02-21 12:29 UTC, mssalvatore commented on monkey/infection_monkey/master/exploiter.py
> +        exploiters_to_run = list(deepcopy(ordered_exploiters))
Iterators can only be used once, so after the loop on lines 61-64, the iterator would be exhausted and all we could return would be an empty iterator.

2022-02-21 12:33 UTC, shreyamalviya commented on monkey/infection_monkey/master/exploiter.py
> +        exploiters_to_run = list(deepcopy(ordered_exploiters))
Oh right. Thanks.

2022-02-21 12:34 UTC, shreyamalviya approved these changes

2022-02-21 12:52 UTC, merged