Agent: Use telemetry messenger in SSH exploit
guardicore/monkey pull request #1727
Opened 2022-02-21 09:59 UTC by ilija-lazoroski

# What does this PR do? 

Fixes #1605. 

Add any further explanations here. 

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...} 
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

2022-02-22 11:38 UTC, shreyamalviya requested changes

2022-02-22 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/i_puppet/i_puppet.py
> +        :param object host: The domain name or IP address of a host
Just a note to remember to solve the circular dependency and change `object` to `VictimHost`.

2022-02-22 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/monkey.py
> +        puppet.load_plugin("SSHExploiter", SSHExploiter, PluginType.EXPLOITER)
This should be constructed here. The plugin can't be loaded into the registry otherwise.

2022-02-22 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/puppet/puppet.py
> +        return exploiter(host, LegacyTelemetryMessengerAdapter(), options).exploit_host()
Parameters should be passed to `exploit_host`, not to the constructor. The object shouldn't be constructed here.

2022-02-22 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/sshexec.py
> +        self._options = options
Is there any reason to initiate these things before the exploiter is run? I don't think there is, so move this logic to the `_exploit_host` function, construct the exploiter object when the plugin is being loaded, and pass the appropriate parameters to this object when the exploiter is actually being run.

2022-02-22 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/HostExploiter.py
> +    ):
This is stale code. `send_exploit_telemetry` (which uses `self.exploit_attempts`) doesn't do anything so calling this function is pointless.

2022-02-22 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/HostExploiter.py
> +    ):
Even if it did, `exploitation_result` and `propagation_result` shouldn't be part of `exploit_attempts`.

2022-02-22 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/puppet/mock_puppet.py
> +        self, name: str, host: object, options: Dict, interrupt: threading.Event
Just a note to remember to solve the circular dependency and change `object` to `VictimHost`.

2022-02-22 12:55 UTC, mssalvatore commented on monkey/infection_monkey/puppet/puppet.py
> +        return exploiter(host, LegacyTelemetryMessengerAdapter(), options).exploit_host()
See https://github.com/guardicore/monkey/pull/1727#discussion_r811915428

2022-02-22 19:49 UTC, mssalvatore requested changes

2022-02-22 19:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
> +                    exploit_result["propagation_success"] = True
This is already set on 147

2022-02-22 19:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
> +                    logger.info(exploit_result["error_message"])
```suggestion
                    logger.error(exploit_result["error_message"])
```

^ But only if it's not empty.

2022-02-22 19:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
> +                exploit_result["propagation_success"] = True
I don't think we can say propagation is true. We're just executing `uname -o`. We haven't successfully launched a monkey yet.

2022-02-22 19:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
> +                exploit_result["propagation_success"] = True
I don't think we can say propagation is true. We're just executing `uname -m`. We haven't successfully launched a monkey yet.

2022-02-22 19:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
> +                logger.debug(exploit_result["error_message"])
```suggestion
                logger.error(exploit_result["error_message"])
```

2022-02-22 19:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
> +            logger.debug(exploit_result["error_message"])
```suggestion
            logger.error(exploit_result["error_message"])
```

2022-02-22 19:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
> +            logger.debug(exploit_result["error_message"])
```suggestion
            logger.error(exploit_result["error_message"])
```

2022-02-23 10:28 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/sshexec.py
> +                self.exploit_result["propagation_success"] = False
These are `False` by default.

2022-02-23 10:28 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/sshexec.py
> +            self.exploit_result["propagation_success"] = False
This is `False` by default.

2022-02-23 10:28 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/sshexec.py
> +            self.exploit_result["propagation_success"] = False
This is `False` by default.

2022-02-23 10:32 UTC, shreyamalviya reviewed
We should also get rid of any stale code in `HostExploiter` now.

2022-02-23 10:43 UTC, shreyamalviya reviewed
Instead of creating a dictionary `exploit_result` and passing everything to `ExploiterResultData` one by one, we could use [default values for named tuples](https://stackoverflow.com/a/18348004), and simply instantiate it as `self.exploit_result = ExploiterResultData` in `pre_exploit()`. Then, we could simply modify that object instead of having a dictionary tracking the exact same values.

2022-02-23 12:12 UTC, mssalvatore commented
> Instead of creating a dictionary `exploit_result` and passing everything to `ExploiterResultData` one by one, we could use [default values for named tuples](https://stackoverflow.com/a/18348004), and simply instantiate it as `self.exploit_result = ExploiterResultData()` in `pre_exploit()`. Then, we could simply modify that object instead of having a dictionary tracking the exact same values.

@shreyamalviya NamedTuples are immutable. We could convert it to a dataclass. The conversion will happen sooner or later, I don't much mind if it happens here or down the road.

2022-02-23 12:14 UTC, shreyamalviya commented
@mssalvatore I'll do it now so we won't have to modify the exploiters again.

2022-02-23 13:15 UTC, shreyamalviya approved these changes

2022-02-23 14:16 UTC, merged