Remove 32-bit references from Hadoop
guardicore/monkey pull request #1748
Opened 2022-02-25 17:53 UTC by shreyamalviya

# What does this PR do?

Fixes a part of #1675 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] ~Is the TravisCI build passing?~
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [ ] ~Have you successfully tested your changes locally? Elaborate:~
    > ~Tested by {Running the Monkey locally with relevant config/running Island/...}~
* [ ] ~If applicable, add screenshots or log transcripts of the feature working~

2022-02-25 19:35 UTC, mssalvatore requested changes
If you follow the chain of calls all the way down, `download_monkey_exe()` Eventually ends up calling `monkey_island/cc/resources/monkey_download.py`, which still has logic regarding 32-bit agents in it. We'll have to remove that in this PR as well.

2022-02-28 07:16 UTC, VakarisZ commented on monkey/infection_monkey/exploit/tools/helpers.py
> +            # if exe not found, and we have the same arch, use our exe
I don't understand this comment, maybe remove it?

2022-02-28 12:42 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/helpers.py
> +            # if exe not found, and we have the same arch, use our exe
Looking into it.

2022-02-28 13:08 UTC, mssalvatore approved these changes
Approved pending a final test by @ilija-lazoroski

2022-02-28 14:52 UTC, merged