1740 add powershell to puppet
guardicore/monkey pull request #1778
Opened 2022-03-11 18:06 UTC by ilija-lazoroski

# What does this PR do?

Fixes #1740 .

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

2022-03-14 05:04 UTC, shreyamalviya commented on monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
> +
Why not just make this a constant?

2022-03-14 12:07 UTC, ilija-lazoroski commented on monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
> +
I don't think it makes a really big difference. Maybe I will change it.

2022-03-16 11:03 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/helpers.py
> +    return f"monkey_temp_bin_{random_string}"
@ilija-lazoroski Nothing uses this besides powershell. I'd recommend changing it to `get_random_file_suffix()` and performing the string concatenation in the powershell exploiter. Other code will need the random file suffix (issue #1782) without the "monkey_temp_bin" part.

2022-03-16 11:44 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/helpers.py
> +    return random_string
This can block indefinitely on Linux if there isn't sufficient entropy to feed `/dev/urandom`. Since this doesn't need to be cryptographically secure, we can just use `random.choices()`.

```suggestion
def get_random_file_suffix() -> str:
    character_set = list(string.ascii_letters + string.digits + "_" + "-")
    return "".join(random.choices(character_set, k=8))
```

2022-03-16 11:50 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/tools/helpers.py
> +    return random_string
We are using `SystemRandom` in the Hadoop exploiter also.

2022-03-16 14:31 UTC, mssalvatore approved these changes
Just missing one code comment.

2022-03-16 14:31 UTC, mssalvatore commented on monkey/infection_monkey/exploit/hadoop.py
> +            [random.choice(string.ascii_lowercase) for _ in range(self.RAN_STR_LEN)]  # noqa: DUO102
Add a comment explaining why we're ignoring DUO102. Because SystemRandom() blocks on Linux.

2022-03-16 15:29 UTC, VakarisZ commented on monkey/infection_monkey/exploit/powershell_utils/powershell_client.py
> +        logger.debug("Successfully authenticated to remote PowerShell service")
Why is this constructor executing commands? Constructor's have one job and it is to construct an object.

2022-03-16 15:40 UTC, VakarisZ commented on monkey/infection_monkey/exploit/powershell.py
> +            raise RemoteAgentCopyError(f"Failed to copy the agent binary to the victim: {ex}")
Where is this caught?

2022-03-16 15:40 UTC, VakarisZ requested changes
See comments

2022-03-16 15:57 UTC, mssalvatore commented on monkey/infection_monkey/exploit/powershell_utils/powershell_client.py
> +        logger.debug("Successfully authenticated to remote PowerShell service")
I added `connect()` to `IPowerShellClient` to resolve this.

2022-03-16 16:02 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/powershell.py
> +            username=".\\dummy_username",
We use second hop on machine 3-48, so when we try to see if the machine is using ssl, we need to use `.\` even if it is a dummy username.

2022-03-16 16:03 UTC, mssalvatore commented on monkey/infection_monkey/exploit/powershell.py
> +            raise RemoteAgentCopyError(f"Failed to copy the agent binary to the victim: {ex}")
On line 84. It doesn't need any special processing by the handler. Reraising as a different exception allows us to add more context. We could also reraise as a generic `Exception`, but this should be ok for now.

2022-03-16 17:09 UTC, mssalvatore approved these changes

2022-03-16 17:13 UTC, mssalvatore commented
@VakarisZ I think all your comments were addressed. We can discuss at planning tomorrow if there's anything outstanding.

2022-03-16 17:13 UTC, merged