1611 interruptable ssh exploit
guardicore/monkey pull request #1789
Opened 2022-03-18 12:08 UTC by ilija-lazoroski

# What does this PR do?

Adds interrupts to SSH exploit

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] ~Is the TravisCI build passing?~
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running SSH exploit and checking timeouts locally.
* [x] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

![image](https://user-images.githubusercontent.com/15820737/159000389-f084d81b-454c-46dd-ae7a-bc34bd620940.png)

2022-03-18 12:32 UTC, VakarisZ commented on monkey/infection_monkey/exploit/sshexec.py
> +SSH_CONNECT_TIMEOUT = 10
What about using timeouts from monkey/common/common_consts/timeouts.py?

2022-03-18 13:16 UTC, VakarisZ commented on monkey/infection_monkey/exploit/sshexec.py
>              with ssh.open_sftp() as ftp:
The default tiemout of this is 1h. This might be a problem

2022-03-18 13:19 UTC, VakarisZ commented on monkey/infection_monkey/exploit/sshexec.py
>              with ssh.open_sftp() as ftp:
Can you do a test? Set a breakpoint at this line, kill the victim and step over. See how long it takes for this line to execute

2022-03-18 13:20 UTC, VakarisZ requested changes
Need you to test one thing, see comments

2022-03-18 13:48 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/sshexec.py
>              with ssh.open_sftp() as ftp:
open_sftp doesn't seem to have timeout .... 

![image](https://user-images.githubusercontent.com/15820737/159014566-63517a08-740f-4861-b249-0e41d4c0f8e1.png)

2022-03-18 14:27 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/sshexec.py
>              with ssh.open_sftp() as ftp:
Actually you are right. If a machine gets killed after we connect, `open_sftp` will wait one hour for a connection and block.

2022-03-21 15:48 UTC, VakarisZ approved these changes
Good job

2022-03-21 16:05 UTC, mssalvatore requested changes

2022-03-21 16:05 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
>                  self.add_vuln_port(port)
Do we still need this call? If so, it's missing from `exploit_with_ssh_keys()`

2022-03-21 16:10 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/sshexec.py
>                  self.add_vuln_port(port)
It is used in smb, wmi and msql. I will add it in `exploit with ssh_keys()`.

2022-03-21 17:44 UTC, mssalvatore requested changes

2022-03-21 17:44 UTC, mssalvatore commented on monkey/infection_monkey/exploit/sshexec.py
>                  _, stdout, _ = ssh.exec_command("uname -o")
Missing timeout

2022-03-21 18:08 UTC, mssalvatore approved these changes

2022-03-21 18:09 UTC, merged