1604 custom pba
guardicore/monkey pull request #1818
Opened 2022-03-25 14:39 UTC by VakarisZ

# What does this PR do?

Includes custom PBA into agent and puppet 

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

2022-03-29 08:12 UTC, shreyamalviya commented on monkey/infection_monkey/post_breach/custom_pba/users_custom_pba.py
>          return False
Consider switching the `if` conditions here too in the way you've done it in `__init__()`.

2022-03-29 08:12 UTC, shreyamalviya commented on monkey/infection_monkey/master/automated_master.py
> +
```suggestion
    def _run_PBAs(
        self, plugins: Iterable[Any], callback: Callable[[Any], None], custom_pba_options: Mapping
    ):
        self._run_plugins(plugins, "post-breach action", callback)

        command, result = self._puppet.run_custom_pba(custom_pba_options)
        telem = PostBreachData(POST_BREACH_FILE_EXECUTION, command, result)
        self._telemetry_messenger.send_telemetry(telem)

```

2022-03-30 12:17 UTC, ilija-lazoroski commented on monkey/infection_monkey/master/automated_master.py
> +from ..post_breach.custom_pba.custom_pba import CustomPBA
Add `CustomPBA` in `__init__` and use it from there. Just for readability and consistency.

2022-03-30 12:27 UTC, ilija-lazoroski commented on monkey/tests/unit_tests/infection_monkey/post_breach/actions/test_users_custom_pba.py
> +from infection_monkey.post_breach.custom_pba.users_custom_pba import UsersPBA
```suggestion
from infection_monkey.post_breach.custom_pba.custom_pba import CustomPBA
```

2022-03-30 12:30 UTC, ilija-lazoroski requested changes
Rebase, fix conflicts,unit tests and retest. Nice job though!

2022-03-30 13:02 UTC, mssalvatore commented on monkey/infection_monkey/post_breach/custom_pba/custom_pba.py
> +            if options["windows_filename"] or options["windows_command"]:
Move to `AutomatedMaster`

2022-03-30 13:08 UTC, mssalvatore commented on monkey/infection_monkey/master/automated_master.py
> +            self._run_plugins([("CustomPBA", custom_pba_options)], "post-breach action", callback)
Try to find a way to avoid coupling the Master to any plugins.

2022-03-30 13:37 UTC, mssalvatore approved these changes

2022-03-30 13:40 UTC, merged