1604 post breach telems accept post breach data
guardicore/monkey pull request #1821
Opened 2022-03-28 12:10 UTC by VakarisZ

# What does this PR do?

Fixes part of #1064, changes telemetries accept post breach data

2022-03-28 14:18 UTC, mssalvatore commented on monkey/infection_monkey/master/automated_master.py
> +        self._telemetry_messenger.send_telemetry(PostBreachTelem(display_name, result))
Display name is, for the moment, a member of `PostBreachData`.
https://github.com/guardicore/monkey/blob/1ec5be908dc1f50cf0c91bf953809154bf6be664/monkey/infection_monkey/i_puppet/i_puppet.py#L37

2022-03-29 07:41 UTC, shreyamalviya requested changes

2022-03-29 07:41 UTC, shreyamalviya commented on monkey/infection_monkey/master/automated_master.py
> +        display_name, result = self._puppet.run_pba(name, options)
This is included in PostBreachData too.
```suggestion
        result = self._puppet.run_pba(name, options)
```

2022-03-29 07:42 UTC, shreyamalviya commented on monkey/infection_monkey/telemetry/post_breach_telem.py
>          :param result: Result of PBA
This needs to be changed too.

2022-03-29 10:26 UTC, merged