1813 bb optimization
guardicore/monkey pull request #1884
Opened 2022-04-13 11:05 UTC by VakarisZ

# What does this PR do?

Fixes #1813

Add any further explanations here.
# Before and after:

Last line `Took X min` represents the time for the whole jenkins job. This gives a perspective of how long the setup process takes in comparison.

## Linux:

Unoptimized, Hadoop 3 failed:
```
FAILED ../envs/monkey_zoo/blackbox/test_blackbox.py::TestMonkeyBlackbox::test_hadoop_exploiter
===== 1 failed, 12 passed, 9 skipped, 1901 warnings in 1137.70s (0:18:57) ======
Black box tests failed!
Took 24 min
```
Unoptimized again, Hadoop 3 failed:
```
=========================== short test summary info ============================
FAILED ../envs/monkey_zoo/blackbox/test_blackbox.py::TestMonkeyBlackbox::test_hadoop_exploiter
===== 1 failed, 12 passed, 9 skipped, 1871 warnings in 1200.87s (0:20:00) ======
Black box tests failed!
Took 26 min
```
Optimized, a lot of failures:
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ../envs/monkey_zoo/blackbox/test_blackbox.py::TestMonkeyBlackbox::test_depth_1_a
FAILED ../envs/monkey_zoo/blackbox/test_blackbox.py::TestMonkeyBlackbox::test_depth_1_b
============ 2 failed, 1 passed, 991 warnings in 680.96s (0:11:20) =============
Black box tests failed!
Took 16 min
```

Windows:

Unoptimized, ssh and tunneling fails:
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
FAILED ..\..\infection_monkey\envs\monkey_zoo\blackbox\test_blackbox.py::TestMonkeyBlackbox::test_ssh_exploiter
FAILED ..\..\infection_monkey\envs\monkey_zoo\blackbox\test_blackbox.py::TestMonkeyBlackbox::test_tunneling
===== 2 failed, 11 passed, 9 skipped, 730 warnings in 1219.55s (0:20:19) ======
Took 34 min
```

Optimized, more tests fail:
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
FAILED ..\..\infection_monkey\envs\monkey_zoo\blackbox\test_blackbox.py::TestMonkeyBlackbox::test_depth_1_a
============ 1 failed, 2 passed, 364 warnings in 718.73s (0:11:58) ============
Took 26 min
```

## Testing Checklist

* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the BB tests manually and from Jenkins

2022-04-13 14:19 UTC, mssalvatore requested changes

2022-04-13 15:55 UTC, mssalvatore approved these changes
LGTM

2022-04-14 08:36 UTC, shreyamalviya approved these changes

2022-04-14 08:56 UTC, ilija-lazoroski commented on envs/monkey_zoo/blackbox/test_blackbox.py
> +        TestMonkeyBlackbox.run_exploitation_test(island_client, Depth3A, "Depth4A test suite")
```suggestion
        TestMonkeyBlackbox.run_exploitation_test(island_client, Depth3A, "Depth3A test suite")
```

2022-04-14 08:59 UTC, ilija-lazoroski approved these changes
One small change. Good job!

2022-04-14 12:13 UTC, merged