Bugfix for 2 edges being created
guardicore/monkey pull request #1932
Opened 2022-05-05 08:27 UTC by shreyamalviya

# What does this PR do?

Fixes #1917 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the Agent and Island as described in the issue.
* [x] If applicable, add screenshots or log transcripts of the feature working

![image](https://user-images.githubusercontent.com/44770317/166886628-e0d9b3b8-cac9-4a2a-8b3c-fed1c9dbfdea.png)

## Explain Changes

Scanning and exploiting happen in parallel and the telemetries for both were being sent too close to each other which was causing a race condition during edge creation.
When `get_or_create_edge()` in `EdgeService` is called the first time, it has to _create_ an edge, but before that is done, it gets called a second time. It can't _get_ the edge the second time either since an edge hasn't been created yet from the first time it was called. So it decides that it needs to _create_ an edge the second time as well and two edges end up being created.

2022-05-05 11:11 UTC, ilija-lazoroski approved these changes

2022-05-05 11:32 UTC, mssalvatore requested changes

2022-05-05 11:32 UTC, mssalvatore commented on monkey/monkey_island/cc/services/edge/edge.py
> +        lock.acquire()
It's safer to use a context manager

```python
with lock:
```

Then you don't have to release it (happens automatically) and you don't have to worry about what happens if you forget to release it. In this case, if line 27 raises any exception besides `DoesNotExist`, the lock will never get released and all future calls to `get_or_create_edge()` will block until the program exits.

2022-05-09 10:26 UTC, mssalvatore approved these changes

2022-05-09 10:28 UTC, merged