1996 remove current server
guardicore/monkey pull request #2015
Opened 2022-06-13 12:28 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #1996 .

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

2022-06-13 14:25 UTC, mssalvatore requested changes
Let's not create a new subpackage (`cc`) yet. When we merge the communication mechanisms, this subpackage won't provide any value.

2022-06-13 17:03 UTC, mssalvatore requested changes
I've made some more comments, but the PR is too large and has at least two distinct goals. Split it up into 2 or more PRs, each of which accomplishes a single goal.

2022-06-14 08:00 UTC, VakarisZ commented
> Let's not create a new subpackage (`cc`) yet. When we merge the communication mechanisms, this subpackage won't provide any value.

I disagree. It makes it easier to find the files that have the same responsibility until then and it costs nothing to move them back. I'm not sure why you say that it won't provide any value once we merge the `control_client` and `control_channel`, because if we do it in extendable way this package will contain more than one file

2022-06-14 09:08 UTC, VakarisZ commented on monkey/tests/unit_tests/infection_monkey/telemetry/conftest.py
> +    monkeypatch.setattr(ControlClient.control_client_object, "send_telemetry", _spy_send_telemetry)
What's the difference? Why do you prefer it that way?

2022-06-14 09:38 UTC, VakarisZ commented
Split up the PR. First part is in https://github.com/guardicore/monkey/pull/2016

2022-06-14 09:38 UTC, closed without merging

2022-06-14 10:14 UTC, ilija-lazoroski commented on monkey/tests/unit_tests/infection_monkey/telemetry/conftest.py
> +    monkeypatch.setattr(ControlClient.control_client_object, "send_telemetry", _spy_send_telemetry)
https://stackoverflow.com/a/47101194 Not really some difference between.

2022-06-14 11:37 UTC, mssalvatore commented on monkey/infection_monkey/control.py
> +    # Ref: infection_monkey.telemetry.base_telem.py
Navigate to a file in GitHub. Click a line. SHIFT+click on a line below to select a block. Click the ellipsis and select "copy permalink"

![image](https://user-images.githubusercontent.com/19957806/173568326-772f9949-a469-41a2-98b2-1cc53d35759f.png)

2022-06-14 11:49 UTC, mssalvatore commented on monkey/tests/unit_tests/infection_monkey/telemetry/conftest.py
> +    monkeypatch.setattr(ControlClient.control_client_object, "send_telemetry", _spy_send_telemetry)
That answer doesn't have anything to do with why I prefer using the MagicMock here.

If you monkey patch the object, then the object still has the capability to do all sorts of things. Monkey patching `send_telemetry()` but leaving all of the other methods intact could result in unexpected behavior down the road if the code decides to try and use any of those methods.

Using a mock object, we're sure it only does the things we've programmed it to do within the confines of what we want to test.

2022-06-14 12:06 UTC, mssalvatore commented
>> Let's not create a new subpackage (cc) yet. When we merge the communication mechanisms, this subpackage won't provide any value.

> I disagree. It makes it easier to find the files that have the same responsibility until then and it costs nothing to move them back. I'm not sure why you say that it won't provide any value once we merge the control_client and control_channel, because if we do it in extendable way this package will contain more than one file

@VakarisZ It may contain more than one file, or it may not. As we simplify the API on the Island, the agent should also become simpler. Adding layers in a hierarchy can add difficulty, so unless there's a distinct benefit to do it, it should be avoided.

In this specific case, it introduces a circular dependency between the parent and child packages. `infection_monkey` depends on `infection_monkey.cc` since `main.py` depends on `control.py`. But `infection_monkey.cc.control.py` depends on `infection_monkey.tunnel`, creating a circular dependency between `infection_monkey` and `infection_monkey.cc`.