1965 mongo credentials repository
guardicore/monkey pull request #2075
Opened 2022-07-08 15:31 UTC by ilija-lazoroski

# What does this PR do?

Implemente `MongoCredentialsRepository`. Related to #1965 

Add any further explanations here.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [x] If applicable, add screenshots or log transcripts of the feature working

2022-07-08 16:17 UTC, mssalvatore requested changes

2022-07-08 16:17 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +            raise RetrievalError(err)
You could reduce duplication by extracting a method that takes a collection as input and returns its contents.

2022-07-08 16:17 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +            raise StorageError(err)
You can reduce duplication by extracting a method that takes a collection and sequence as input and puts the sequence into the collection.

2022-07-08 16:17 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +            raise RemovalError(err)
You can reduce duplication by extracting a method that takes a collection as input and clears it.

2022-07-08 16:17 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +from monkey_island.cc.database import mongo
Don't use global state! Write a constructor that takes a mongo connection.

2022-07-08 16:17 UTC, mssalvatore commented on monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_credentials_repository.py
> +    mongo_repository.remove_configured_credentials()
reduce duplication

2022-07-08 17:48 UTC, mssalvatore requested changes

2022-07-08 17:48 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +from flask_pymongo import PyMongo
Use [pymongo](https://pymongo.readthedocs.io/en/stable/) instead of flask_pymongo.

2022-07-08 17:48 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +        self._mongo = mongo_db
Give these the same name.

2022-07-08 17:48 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +            raise RetrievalError(err)
Move the error handling down into `_get_credentials_from_collection()` to reduce duplication. Do this for the rest of the methods, too.

2022-07-08 17:48 UTC, mssalvatore commented on monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_credentials_repository.py
> +def fake_mongo_repository(monkeypatch):
What's fake about the repository?

2022-07-08 17:48 UTC, mssalvatore commented on monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_credentials_repository.py
> +def fake_mongo_repository(monkeypatch):
```suggestion
def fake_mongo_repository():
```

2022-07-08 17:48 UTC, mssalvatore commented on monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_credentials_repository.py
> +    mongo = mongoengine.connection.get_connection()
Does this work without an actual instance of mongo running?

2022-07-11 06:28 UTC, VakarisZ commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +
Why is there a newline?

2022-07-11 06:28 UTC, VakarisZ commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +            raise RetrievalError(err)
Both of these methods are exactly the same, except the collection name

2022-07-11 06:32 UTC, VakarisZ commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +            raise StorageError(err)
These two methods are exactly the same, except the collection name

2022-07-11 06:39 UTC, VakarisZ reviewed
In general looks good, except the duplication between the methods. Also, nothing forces us to store us stolen and configured on the separate collections, we could store it in one but filter when deleting/fetching.

2022-07-11 12:06 UTC, mssalvatore commented on monkey/monkey_island/cc/services/initialize.py
> +    mongo = MongoClient(MONGO_URL, serverSelectionTimeoutMS=100)
Add this object to the DI container so future repositories can use the same connection.

2022-07-11 12:07 UTC, mssalvatore commented on monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_credentials_repository.py
> +]
Why create dictionaries and then use `from_mapping()`? Why not just create objects and use them?

2022-07-11 12:11 UTC, mssalvatore commented on monkey/monkey_island/cc/repository/mongo_credentials_repository.py
> +from pymongo import MongoClient
`pymongo` isn't an explicit dependency of monkey island. I've added it to the `Pipfile`.

2022-07-11 13:28 UTC, merged