2176 remove credentials intercepting telemetry messenger
guardicore/monkey pull request #2197
Opened 2022-08-15 12:47 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #2176 .

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2022-08-16 08:12 UTC, shreyamalviya approved these changes

2022-08-16 08:19 UTC, shreyamalviya requested changes

2022-08-16 08:19 UTC, shreyamalviya commented on monkey/infection_monkey/monkey.py
> +        zerologon_wrapper = ExploiterWrapper(self._telemetry_messenger, agent_repository)
This isn't needed anymore. We only had a separate wrapper for Zerologon because it stole credentials. We can remove this now.

2022-08-17 06:05 UTC, shreyamalviya approved these changes

2022-08-18 10:39 UTC, mssalvatore approved these changes

2022-08-18 10:39 UTC, merged