2176 modify zerologon to publish events
guardicore/monkey pull request #2198
Opened 2022-08-15 16:01 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #2176 .

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2022-08-16 08:20 UTC, shreyamalviya requested changes

2022-08-16 08:20 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon.py
> +            tags=({"ZerologonCredentialsStolen"}),
Extract to constant

2022-08-16 08:20 UTC, shreyamalviya commented on monkey/infection_monkey/monkey.py
> +        )
`CredentialsInterceptingTelemetryMessenger` is being removed in #2197. I believe `zerologon_wrapper` won't be needed after that is merged. Just rebase on that branch and remove this change to avoid having to resolve conflicts later.

2022-08-16 08:20 UTC, shreyamalviya commented on monkey/infection_monkey/monkey.py
> +        )
See https://github.com/guardicore/monkey/pull/2197#discussion_r946474216

2022-08-16 12:27 UTC, mssalvatore requested changes

2022-08-16 12:27 UTC, mssalvatore commented on monkey/infection_monkey/exploit/zerologon.py
> +ZEROLOGON_EXPLOIT_TAG = "ZerologonCredentialsStolen"
Make tags all lower case.

I don't know that this tag is useful. A more useful tag would just be `zerologon-exploiter`. We already know credentials were stolen, since the event is a `CredentialsStolenEvent`

2022-08-16 12:27 UTC, mssalvatore commented on monkey/infection_monkey/exploit/zerologon.py
> +            tags=(ZEROLOGON_EVENT_TAGS),
What attack techniques were used to generate this event? It's worth taking a good, long look through the MITRE ATT&CK framework to find them all.

2022-08-16 16:51 UTC, mssalvatore commented on monkey/infection_monkey/exploit/zerologon.py
> +            tags=(ZEROLOGON_EVENT_TAGS),
We will. For now, let's make sure all relevant tags are included. The report can ignore any it doesn't know how to handle.

2022-08-16 17:00 UTC, mssalvatore commented on monkey/infection_monkey/exploit/zerologon.py
> +            target=None,
`target` is defaulted to `None` if you rebase on`develop`

2022-08-16 17:04 UTC, mssalvatore commented on monkey/infection_monkey/monkey.py
> +        )
+1

2022-08-17 06:16 UTC, shreyamalviya requested changes

2022-08-17 06:16 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon.py
> +ZEROLOGON_EVENT_TAGS = {ZEROLOGON_EXPLOIT_TAG, T1003_TAG, T1098_TAG}
Tags need to be named consistently across files. See https://github.com/guardicore/monkey/blob/eec48e9cd8603313d3d4b489166fe50430e06c1f/monkey/infection_monkey/credential_collectors/ssh_collector/ssh_handler.py#L18..L28.

2022-08-17 06:16 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon.py
> +ZEROLOGON_EVENT_TAGS = {ZEROLOGON_EXPLOIT_TAG, T1003_TAG, T1098_TAG}
```suggestion
ZEROLOGON_EXPLOITER_TAG = "zerologon-exploiter"
T1003_ATTACK_TECHNIQUE_TAG = "attack-t1003"
T1098_ATTACK_TECHNIQUE_TAG = "attack-t1098"


ZEROLOGON_EVENT_TAGS = {ZEROLOGON_EXPLOITER_TAG, T1003_ATTACK_TECHNIQUE_TAG, T1098_ATTACK_TECHNIQUE_TAG}
```

2022-08-17 10:34 UTC, shreyamalviya approved these changes

2022-08-17 11:39 UTC, mssalvatore commented on monkey/infection_monkey/exploit/zerologon.py
> +}
```suggestion
ZEROLOGON_EVENT_TAGS = frozenset((
    ZEROLOGON_EXPLOITER_TAG,
    T1003_ATTACK_TECHNIQUE_TAG,
    T1098_ATTACK_TECHNIQUE_TAG,
))
```

2022-08-17 11:39 UTC, mssalvatore commented on monkey/infection_monkey/exploit/zerologon.py
> +            tags=(ZEROLOGON_EVENT_TAGS),
```suggestion
            tags=ZEROLOGON_EVENT_TAGS,
```

2022-08-17 12:08 UTC, mssalvatore approved these changes

2022-08-17 12:08 UTC, merged