1242 allow custom ransomware extension
guardicore/monkey pull request #2206
Opened 2022-08-18 15:45 UTC by cakekoa

# What does this PR do?

Contributes to #1242

Addresses all changes except for updating the documentation.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by Running the Monkey locally with relevant config/running Island/...
       as well as by running the new unit tests
* [ ] If applicable, add screenshots or log transcripts of the feature working
   ![Screen Shot 2022-08-18 at 11 37 13 AM](https://user-images.githubusercontent.com/11077625/185436228-6680a170-50e1-43a0-94cc-f3cfd69ca5c5.jpg)
   ```
   $ ls /tmp/random
   file.txt  some_data.tar
   
   $ python3.7 ./infection_monkey.py m0nk3y -s <server:port>
   ...
   2022-08-18 15:41:46,271 [141255:PayloadThread:DEBUG] ransomware_builder.build_ransomware.26: Ransomware configuration:
   {'encryption': {'directories': {'linux_target_dir': '/tmp/random',
                                   'windows_target_dir': ''},
                   'enabled': True,
                   'file_extension': '.m0nk3y.dory'},
    'other_behaviors': {'readme': True}}
   2022-08-18 15:41:46,272 [141255:PayloadThread:INFO] ransomware.run.43: Running ransomware payload
   2022-08-18 15:41:46,272 [141255:PayloadThread:INFO] ransomware._find_files.53: Collecting files in /tmp/random
   2022-08-18 15:41:46,272 [141255:PayloadThread:INFO] ransomware._encrypt_files.57: Encrypting files in /tmp/random
   2022-08-18 15:41:46,272 [141255:PayloadThread:DEBUG] ransomware._encrypt_files.62: Encrypting /tmp/random/file.txt
   2022-08-18 15:41:46,275 [141255:PayloadThread:DEBUG] ransomware._encrypt_files.62: Encrypting /tmp/random/some_data.tar
   2022-08-18 15:41:46,961 [141255:PayloadThread:INFO] readme_dropper.leave_readme.13: Leaving a ransomware README file at /tmp/random/README.txt
   ...
   
   $ ls /tmp/random
   file.txt.m0nk3y.dory  README.txt  some_data.tar.m0nk3y.dory
   ```

2022-08-18 15:51 UTC, cakekoa commented
I could add more allowable file extension characters. It's currently only accepting letters, numbers, and underscores. Dots are allowed as well (chained file extensions)

2022-08-18 17:09 UTC, mssalvatore requested changes

2022-08-18 17:09 UTC, mssalvatore commented on monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_ransomware.py
> +    with tempfile.TemporaryDirectory() as tmpdir:
There's a pytest fixture for temporary paths that might be better.

2022-08-18 17:52 UTC, cakekoa commented on monkey/infection_monkey/payload/ransomware/ransomware_builder.py
> +        targeted_file_extensions.discard(EXTENSION)
Oh, yes, nice catch!

2022-08-19 07:48 UTC, ilija-lazoroski approved these changes
I think it needs a Changelog entry otherwise good job!

2022-08-19 12:51 UTC, mssalvatore commented
> I think it needs a Changelog

+1

2022-08-19 13:48 UTC, mssalvatore approved these changes

2022-08-19 13:48 UTC, merged