2216 pass servers to exploiters
guardicore/monkey pull request #2243
Opened 2022-09-02 14:16 UTC by ilija-lazoroski

# What does this PR do?

Fixes #`put issue number here`.

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2022-09-02 15:43 UTC, mssalvatore requested changes

2022-09-02 15:43 UTC, mssalvatore commented on monkey/infection_monkey/exploit/HostExploiter.py
> +        servers: List[str],
```suggestion
        servers: Sequence[str],
```

2022-09-02 15:43 UTC, mssalvatore commented on monkey/infection_monkey/exploit/exploiter_wrapper.py
> +            servers: List[str],
```suggestion
            servers: Sequence[str],
```

2022-09-02 15:43 UTC, mssalvatore commented on monkey/infection_monkey/exploit/exploiter_wrapper.py
> +            servers: List[str],
Servers need to be passed to the exploiter every time the exploiter is run. The list of servers may change over time.

2022-09-05 12:38 UTC, mssalvatore commented
How was this tested?

2022-09-05 13:09 UTC, VakarisZ commented on monkey/infection_monkey/master/exploiter.py
> +        servers: Sequence[str],
Maybe it's worth moving the servers to be object property? Most of Exploiter methods seem to use this parameter

2022-09-05 13:26 UTC, VakarisZ commented on monkey/infection_monkey/master/exploiter.py
> +        servers: Sequence[str],
Perhaps not, but these method definitions are growing larger and larger. This class pass around a bunch of parameters it doesn't use and it doesn't need to know depth, servers or targets. It needs to know  only stop event and victim OS by the looks of it

2022-09-05 13:27 UTC, VakarisZ approved these changes

2022-09-05 14:03 UTC, mssalvatore commented on monkey/infection_monkey/master/exploiter.py
> +        servers: Sequence[str],
In the future, the list of severs may be updated with the list of all known servers from the island. The exploiter needs to be able to receive an updated list every time it runs.

2022-09-05 14:04 UTC, mssalvatore approved these changes

2022-09-05 14:04 UTC, merged