2234 refactor reset agent config
guardicore/monkey pull request #2276
Opened 2022-09-12 14:02 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #2234 .

Task to refatctor  `reset_agent_configuration` and publish an event from the endpoint `reset_agent_configuration`

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

![image](https://user-images.githubusercontent.com/15820737/189673903-7af0c06f-3a60-4ab2-af1a-a3ff4f55ca03.png)

2022-09-12 15:24 UTC, mssalvatore requested changes

2022-09-12 15:24 UTC, mssalvatore commented on monkey/tests/unit_tests/monkey_island/cc/services/test_reset_agent_configuration.py
> +    return reset_agent_configuration(agent_configuration_repository, mock_file_repository)
Missing typehints

2022-09-12 15:24 UTC, mssalvatore commented on monkey/monkey_island/cc/services/reset_agent_configuration.py
> +class reset_agent_configuration:
Missing docstrings

2022-09-12 17:38 UTC, mssalvatore commented on monkey/monkey_island/cc/resources/reset_agent_configuration.py
> +        self._event_queue = event_queue
```suggestion
    def __init__(self, island_event_queue: IIslandEventQueue):
        self._island_event_queue = island_event_queue
```

2022-09-13 08:23 UTC, shreyamalviya approved these changes

2022-09-13 08:55 UTC, merged