Island, Agent: Move local IP and interface retrieval to common
guardicore/monkey pull request #2298
Opened 2022-09-15 10:01 UTC by VakarisZ

Both, island and agent needs to get local IP's/interfaces. We should also consider merging them, since interfaces also contain IP's

# What does this PR do?

Fixes #2216

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2022-09-15 11:47 UTC, mssalvatore requested changes
None of these functions should have `local` in the name. If interfaces have public IPs (not local network IPs), the function will return them. Furthermore, the functions filter out the loopback interface, which is traditionally considered a local interface.

Use `get_network_interfaces()`

2022-09-15 14:49 UTC, VakarisZ commented
I'm not sure what's a better name to indicate that we are getting ip's of the current/local machine (not victim host or anything).

2022-09-16 11:17 UTC, mssalvatore commented
> I'm not sure what's a better name to indicate that we are getting ip's of the current/local machine (not victim host or anything).

What about `get_system_ips()`?

2022-09-16 13:10 UTC, mssalvatore approved these changes

2022-09-16 13:12 UTC, merged