2269 publish events from hadoop exploiter
guardicore/monkey pull request #2396
Opened 2022-10-04 18:34 UTC by cakekoa

# What does this PR do?

Fixes part of #2269.

Update Hadoop exploiter to publish propagation and exploitation events.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ]~~ Was the CHANGELOG.md updated to reflect the changes?~~
* [ ] ~~Was the documentation framework updated to reflect the changes?~~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~~Added relevant unit tests?~~
* [ ] ~~Have you successfully tested your changes locally? Elaborate:~~
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] ~~If applicable, add screenshots or log transcripts of the feature working~~

2022-10-05 09:56 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/hadoop.py
> +                tags=PROPAGATION_TAGS,
Why propagation tags when we publish an exploitation event?

2022-10-05 12:26 UTC, cakekoa commented on monkey/infection_monkey/exploit/hadoop.py
> +                tags=PROPAGATION_TAGS,
Good catch -- fixed!

2022-10-05 14:33 UTC, mssalvatore requested changes
Left some questions. A big question, though, is this:

Do we need to check for vulnerable URLs? Why not just exploit stuff until we succeed? It seems unnecessary. Maybe @VakarisZ has some insight on the history.

2022-10-05 14:33 UTC, mssalvatore commented on monkey/infection_monkey/exploit/hadoop.py
> +            )
Timestamps need to be recorded as close to the actual event as possible.

2022-10-05 14:33 UTC, mssalvatore commented on monkey/infection_monkey/exploit/hadoop.py
> +            )
What about on failure?

```suggestion
        self._publish_exploitation_event(
            target=self.host.ip_addr,
            exploitation_success=success,
            tags=EXPLOIT_TAGS,
        )
```

2022-10-05 14:33 UTC, mssalvatore commented on monkey/infection_monkey/exploit/hadoop.py
> +            )
I think just do this in `exploit()`. See also comments on timestamps.

2022-10-05 14:33 UTC, mssalvatore commented on monkey/infection_monkey/exploit/hadoop.py
> +            )
Timestamps

2022-10-05 14:47 UTC, VakarisZ commented
> Left some questions. A big question, though, is this:
> 
> Do we need to check for vulnerable URLs? Why not just exploit stuff until we succeed? It seems unnecessary, since exploit and check do basically the same thing with a different command. Maybe @VakarisZ has some insight on the history.

I don't think there's any reason besides consistency. If we want to change it we will need to reeavaluate exploitation indicators. I don't remember if a response to exploitation request needs to be 200 or it can be 500. I also don't remember if all or only exploited responses include `application-id`

2022-10-06 09:12 UTC, shreyamalviya reviewed
Same comments as https://github.com/guardicore/monkey/pull/2401

2022-10-06 16:00 UTC, mssalvatore requested changes

2022-10-07 12:38 UTC, mssalvatore requested changes

2022-10-07 12:38 UTC, mssalvatore commented on monkey/infection_monkey/exploit/hadoop.py
> +            if self.exploit(potential_urls[0], command):
We need to try all potential URLs.

2022-10-07 13:37 UTC, mssalvatore approved these changes

2022-10-07 13:38 UTC, merged