2269 publish events from log4shell exploiter
guardicore/monkey pull request #2397
Opened 2022-10-04 18:35 UTC by cakekoa

# What does this PR do?

Fixes part of #2269.

Update log4shell exploiter to publish propagation and exploitation events.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] ~~Was the CHANGELOG.md updated to reflect the changes?~~
* [ ] ~~Was the documentation framework updated to reflect the changes?~~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~~Added relevant unit tests?~~
* [ ] ~~Have you successfully tested your changes locally? Elaborate:~~
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] ~~If applicable, add screenshots or log transcripts of the feature working~~

2022-10-05 15:25 UTC, mssalvatore requested changes
I'm torn on whether the event publishing should go in `_wait_for_victim()` or stay where it is down in the different wait methods. Let's take another look once we shorten the publish calls.

2022-10-05 15:25 UTC, mssalvatore commented on monkey/infection_monkey/exploit/log4shell.py
> +                    f"potential {exploit.service_name} service: {err}"
This isn't working as expected. Run the below example as a test:

```python
import time

error_message = "The first part of the "
f"error message {time.time()}"

print(error_message)
```

Fix with:
 ```suggestion
                    error_message = (
                        "An error occurred while attempting to exploit log4shell on a "
                        f"potential {exploit.service_name} service: {err}"
                    )
```

Black will probably have something to say about that formatting.

2022-10-05 15:25 UTC, mssalvatore commented on monkey/infection_monkey/exploit/log4shell.py
>                      url = exploit.trigger_exploit(self._build_ldap_payload(), self.host, port)
I think timestamp for exploitation should be recorded here.

2022-10-05 15:25 UTC, mssalvatore commented on monkey/infection_monkey/exploit/log4shell.py
> +                )
Using the current timestamp actually makes sense here, I think.

👍

2022-10-05 19:11 UTC, cakekoa commented on monkey/infection_monkey/exploit/log4shell.py
> +        )
It _would_ if `build_monkey_commandline()` wasn't lying about its interface -- it actually accepts any argument and calls `str()` on it

2022-10-06 09:10 UTC, shreyamalviya reviewed
Same comments as https://github.com/guardicore/monkey/pull/2401

2022-10-06 21:26 UTC, merged