2269 publish events for mssql exploiter
guardicore/monkey pull request #2401
Opened 2022-10-05 13:32 UTC by cakekoa

# What does this PR do?

Fixes part of #2269.

Updates the MSSQL exploiter to publish exploitation and propagation events.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] ~~Was the CHANGELOG.md updated to reflect the changes?~~
* [ ] ~~Was the documentation framework updated to reflect the changes?~~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~~Added relevant unit tests?~~
* [ ] ~~Have you successfully tested your changes locally? Elaborate:~~
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] ~~If applicable, add screenshots or log transcripts of the feature working~~

2022-10-05 16:41 UTC, mssalvatore requested changes
Fix timestamps

2022-10-05 16:41 UTC, mssalvatore commented on monkey/infection_monkey/exploit/mssqlexec.py
> +    T1071_ATTACK_TECHNIQUE_TAG,
This technique is for command and control. I think this would be more like if the Island were using MSSQL to communicate and send instructions to the agent.

2022-10-05 16:41 UTC, mssalvatore commented on monkey/infection_monkey/exploit/mssqlexec.py
> +            )
Isn't this redundant? The failed event will already be published by `_report_login_attempt()`.

2022-10-06 09:08 UTC, shreyamalviya requested changes
I think you meant to modify HostExploiter.py as well. The event publishing won't work right now.

2022-10-06 09:08 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/mssqlexec.py
> +
Being used where?

2022-10-06 09:08 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/mssqlexec.py
> +        stamp = time()
```suggestion
        timestamp = time()
```

2022-10-07 06:36 UTC, shreyamalviya approved these changes

2022-10-07 12:46 UTC, merged