2269 publish events from zerologon
guardicore/monkey pull request #2404
Opened 2022-10-05 15:11 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #2269.

Tasks left:
- [ ] Publish `PasswordRestorationEvent` after that is merged
- [ ] Assert that correct events where published in the UT
- [ ] Review timestamps on events.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [x] If applicable, add screenshots or log transcripts of the feature working

2022-10-06 06:57 UTC, VakarisZ commented on monkey/infection_monkey/exploit/zerologon.py
> +                )
This method doesn't attempt any exploitations?

2022-10-06 06:59 UTC, VakarisZ commented on monkey/infection_monkey/exploit/zerologon.py
> +            exploitation_success=False,
`exploit_attempt_result` might be successful?

2022-10-06 07:12 UTC, VakarisZ commented on monkey/infection_monkey/exploit/zerologon.py
> +        except BaseException as err:
Don't use `BaseException`. It will catch system errors and keyboard interrupts. It's a one-way ticket to a hanging process

2022-10-06 07:31 UTC, VakarisZ approved these changes
One change

2022-10-06 08:03 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon_utils/vuln_assessment.py
> +        )
Why are we publishing an event in here? Why not do it in the ZerologonExploiter class itself? It makes sense to me that this function's job is to check if the machine is exploitable, and that anything to do with the exploiter in the Agent, data gathered, events carried out, etc, is the job of the exploiter class.

2022-10-06 09:06 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/zerologon.py
> +    T1098_ATTACK_TECHNIQUE_TAG,
We need to advise any technique that the exploiter is doing. We will revise later all processing/UI code for all techniques so in this way we will know what we need to do.

2022-10-06 09:07 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/zerologon.py
> +        )
Those changed. I will need to rebase.

2022-10-06 09:08 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/zerologon_utils/vuln_assessment.py
> +        )
The thing is that every check of if a target is exploitable is a exploitation event so we need to record that. I didn't see any other way of doing it..

2022-10-06 10:52 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon_utils/vuln_assessment.py
> +        )
I'm removing these from here for now.

2022-10-06 11:09 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/zerologon.py
> +                    time=time(),
I think you don't need `time=time()` as `time()` is already a default when publishing an events.

2022-10-07 06:10 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon.py
> +        )
This is unnecessary and repetitive in the failing case. We're publishing an exploitation event in `assess_exploit_attempt()` after this.

2022-10-07 08:43 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/zerologon.py
> +        )
The `assess exploit_attempt` publishes an events if we have any exploit result. The above covers if we don't have any exploitation result for some reason.

2022-10-07 11:38 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon.py
> +        )
Let's move this to `assess_exploit_attempt()` for readability, then.

2022-10-07 14:14 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/zerologon.py
> +        )
I would not like to move it there because in that case, we are losing the error message that happened when we don't have exploit result.

2022-10-10 09:35 UTC, shreyamalviya requested changes

2022-10-10 09:35 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon.py
> +                self._publish_exploitation_event(timestamp, False, error_message=error_message)
Add log statement?

2022-10-10 09:35 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon.py
> +    def try_exploit_attempt(self, rpc_con) -> Tuple[Optional[object], float]:
The "exploit" is the whole process of authenticating and changing the password, not just the latter. Let's rename this and everything else that is similarly relevant to use "change_password" instead of using "exploit".

2022-10-10 09:35 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/zerologon_utils/vuln_assessment.py
> +def connect_to_dc(dc_ip) -> object:
Let's just move all this code to the exploit file. Or at least rename it to something more appropriate.

2022-10-10 12:51 UTC, shreyamalviya commented on monkey/tests/unit_tests/infection_monkey/exploit/zerologon_utils/test_dc_utils.py
> +def test_dc_utils__get_dc_details_multiple_netbios_names(host, monkeypatch):
Why have the file name in the test name?
```suggestion
def test_get_dc_details_multiple_netbios_names(host, monkeypatch):
```

2022-10-10 14:50 UTC, mssalvatore approved these changes

2022-10-10 15:13 UTC, merged