2269 publish events from smbexec exploiter
guardicore/monkey pull request #2406
Opened 2022-10-06 16:31 UTC by cakekoa

# What does this PR do?

Fixes part of #2269.

Updates smbexec exploiter to publish exploitation and propagation events.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] ~~Was the CHANGELOG.md updated to reflect the changes?~~
* [ ] ~~Was the documentation framework updated to reflect the changes?~~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~~Added relevant unit tests?~~
* [ ] ~~Have you successfully tested your changes locally? Elaborate:~~
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] ~~If applicable, add screenshots or log transcripts of the feature working~~

2022-10-07 06:26 UTC, shreyamalviya requested changes

2022-10-07 06:26 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/smbexec.py
> +
```suggestion
    _EXPLOITER_TAGS = (
        SMBEXEC_EXPLOITER_TAG,
        T1021_ATTACK_TECHNIQUE_TAG,
        T1110_ATTACK_TECHNIQUE_TAG,
        T1210_ATTACK_TECHNIQUE_TAG,
    )
    _PROPAGATION_TAGS = (
        SMBEXEC_EXPLOITER_TAG,
        T1021_ATTACK_TECHNIQUE_TAG,
        T1105_ATTACK_TECHNIQUE_TAG,
        T1210_ATTACK_TECHNIQUE_TAG,
    )

```

2022-10-07 07:08 UTC, shreyamalviya approved these changes

2022-10-07 08:36 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/smbexec.py
> +                self._publish_exploitation_event(timestamp, False, error_message=message)
```suggestion
                error_message = (
                    f"Error while trying to copy file using SMB to {self.host.ip_addr} with "
                    f"{creds_for_log}:{exc}"
                )
                logger.error(error_message)
                self._publish_exploitation_event(timestamp, False, error_message=error_message)
```

2022-10-07 10:51 UTC, ilija-lazoroski requested changes
Timestamps

2022-10-07 10:51 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/smbexec.py
> +            timestamp = time()
With this approach, both exploitation and propagation will have the same timestamp which is wrong.

2022-10-07 12:36 UTC, cakekoa commented on monkey/infection_monkey/exploit/smbexec.py
> +            timestamp = time()
As discussed, we will use the timestamp from when we copy the file for propagation. We will re-evaluate if/when we add events for copying the file.

2022-10-10 12:49 UTC, mssalvatore requested changes

2022-10-10 12:49 UTC, mssalvatore commented on monkey/infection_monkey/exploit/smbexec.py
> +            return self.exploit_result
Publish propagation failed

2022-10-10 12:50 UTC, ilija-lazoroski commented on monkey/infection_monkey/exploit/smbexec.py
> +            return self.exploit_result
on it

2022-10-10 15:14 UTC, merged