2269 update reports with exploitation events
guardicore/monkey pull request #2414
Opened 2022-10-10 20:47 UTC by cakekoa

# What does this PR do?

Fixes part of #2269.

Updates the issues reports. This affects the "Security Findings" > "Potential Security Issues" list, as well as the recommendations.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] ~~Was the CHANGELOG.md updated to reflect the changes?~~
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~~Added relevant unit tests?~~
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2022-10-11 10:50 UTC, shreyamalviya requested changes

2022-10-11 10:50 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/report-components/security/issues/SshIssue.js
> +          className="badge badge-info" style={{ margin: '2px' }}>{issue.ip_address}</span>) is vulnerable to a <span
```suggestion
          className="badge badge-info" style={{ margin: '2px' }}>{issue.ip_address}</span>) is vulnerable to an <span
```

2022-10-11 10:50 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/report-components/security/issues/SshIssue.js
> +          className="badge badge-info" style={{ margin: '2px' }}>{issue.ip_address}</span>) is vulnerable to a <span
```suggestion
          className="badge badge-info" style={{ margin: '2px' }}>{issue.ip_address}</span>) is vulnerable to an <span
```

2022-10-11 10:50 UTC, shreyamalviya commented on monkey/monkey_island/cc/services/reporting/report.py
> +        target_machine = cls._machine_repository.get_machines_by_ip(exploit.target)[0]
I don't understand this logic. Why is the first machine always the one we want?

2022-10-11 10:50 UTC, shreyamalviya commented on monkey/monkey_island/cc/services/reporting/report.py
> +        return [cls.process_exploit_event(e, password_restored).__dict__ for e in filtered_exploits]
Use `dataclasses.asdict()` instead of `.__dict__`.

2022-10-11 11:59 UTC, mssalvatore commented on monkey/monkey_island/cc/services/reporting/report.py
> +        target_machine = cls._machine_repository.get_machines_by_ip(exploit.target)[0]
IPs are not unique, but we're treating them like they are for now. This is an assumption we're making throughout the code until we can come up with a reliable way to disambiguate IP addresses.

2022-10-12 15:21 UTC, VakarisZ reviewed
Ideally, the file `services/reporting/report.py` should not exist. I don't think it's necessary to migrate it to UI now, focusing on one thing at a time is fine.

2022-10-12 15:35 UTC, VakarisZ commented on monkey/monkey_island/cc/ui/src/components/report-components/security/issues/WmiIssue.js
> +      Change user passwords to a complex one-use password that is not shared with other computers on the network.
What about the pass the hash?

2022-10-12 15:39 UTC, VakarisZ approved these changes
Haven't found anything worthvile after a quick glance

2022-10-13 10:22 UTC, ilija-lazoroski commented on monkey/monkey_island/cc/services/reporting/report.py
> +        cls, exploit: ExploitationEvent, password_restored: Dict[ipaddress.IPv4Address, bool]
```suggestion
        cls, exploitation_event: ExploitationEvent, password_restored: Dict[ipaddress.IPv4Address, bool]
```

2022-10-13 10:23 UTC, ilija-lazoroski commented on monkey/monkey_island/cc/services/reporting/report.py
> +        exploits: Iterable[ExploitationEvent],
```suggestion
        exploitation_events: Iterable[ExploitationEvent],
```

2022-10-13 10:24 UTC, ilija-lazoroski approved these changes
Some simple renaming and LGTM!

2022-10-13 11:57 UTC, merged