2269 remove exploit telem
guardicore/monkey pull request #2436
Opened 2022-10-13 20:13 UTC by cakekoa

# What does this PR do?

Fixes part of #2269.

Removes ExploitTelem.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] ~~Was the CHANGELOG.md updated to reflect the changes?~~
* [ ] ~~Was the documentation framework updated to reflect the changes?~~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~~Added relevant unit tests?~~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running in the zoo environment
* [x] If applicable, add screenshots or log transcripts of the feature working
    > ![Screen Shot 2022-10-13 at 4 08 05 PM](https://user-images.githubusercontent.com/11077625/195699806-07495cb7-91be-4419-9648-d62fd4377288.jpg)
    > ![Screen Shot 2022-10-13 at 4 09 52 PM](https://user-images.githubusercontent.com/11077625/195699972-290dced1-2480-4f5c-97f0-bad2916c4924.jpg)
    > ![Screen Shot 2022-10-13 at 4 08 44 PM](https://user-images.githubusercontent.com/11077625/195699851-3df32aef-58d7-41c9-ae3d-11211ba6b8c8.jpg)
    > ![Screen Shot 2022-10-13 at 4 09 23 PM](https://user-images.githubusercontent.com/11077625/195699898-0997cfb4-13e8-499a-8dec-f786eb136e1f.jpg)

2022-10-14 08:40 UTC, VakarisZ requested changes
Exploit telemetries are still being used in `monkey/monkey_island/cc/resources/monkey.py:49`. If that endpoint is no longer relevant, we should remove it here

2022-10-14 08:41 UTC, VakarisZ commented
`test_monkey_exploitation.py` also using it

2022-10-14 08:43 UTC, VakarisZ commented
There are a bunch of ATT&CK technique reports also querying this type of telemetry

2022-10-14 13:25 UTC, cakekoa commented
Let me know if you think this is appropriate:
  - I will remove the code pertaining to exploits in the Monkey resource. It appears that the database that it updates is used in a number of places still, and we can reconsider removing it when we rework the map.
  - I have removed `test_monkey_exploitation.py` as well as the method that it tested.
  - As we discussed, since ATT&CK report is being removed, I think we can just skip any changes here for now.

2022-10-17 06:01 UTC, shreyamalviya approved these changes

2022-10-17 08:17 UTC, VakarisZ commented
> Let me know if you think this is appropriate:
> 
> * I will remove the code pertaining to exploits in the Monkey resource. It appears that the database that it updates is used in a number of places still, and we can reconsider removing it when we rework the map.
> * I have removed `test_monkey_exploitation.py` as well as the method that it tested.
> * As we discussed, since ATT&CK report is being removed, I think we can just skip any changes here for now.

1. OK
2. OK
3. Make sure that other functionality is not broken by this, for example, there should be no 500 errors when I go to the report/map etc.

2022-10-17 08:18 UTC, VakarisZ commented on monkey/monkey_island/cc/resources/monkey.py
> +                parent_to_add = (parent, None)
I don't think we can do it yet without breaking the report

2022-10-17 13:44 UTC, merged