Fix empty log file download bug
guardicore/monkey pull request #2687
Opened 2022-12-13 10:27 UTC by shreyamalviya

# What does this PR do?

Fixes #2586 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the Island
* [x] If applicable, add screenshots or log transcripts of the feature working

![image](https://user-images.githubusercontent.com/44770317/207293265-b40c35bd-fdb8-4cc3-91f6-000d22ee0f92.png)

2022-12-13 12:41 UTC, mssalvatore requested changes
My concern here is that there's nothing that will make that text go away. The UI won't know if the file magically reappears and becomes downloadable. In other words, I think this error needs to be somehow "dismissible" by the user.

I'm thinking we should do something more like this: 
![image](https://user-images.githubusercontent.com/19957806/207320189-16e46821-c342-4777-8239-ec057c126c6d.png)

You can use a [Bootstrap Alert](https://getbootstrap.com/docs/4.2/components/alerts/) to do it.

I think @VakarisZ had some other ideas about how to display the error in a dismissible way.

2022-12-14 09:17 UTC, shreyamalviya commented
![image](https://user-images.githubusercontent.com/44770317/207555582-ad397471-90f8-4869-9f03-daf41cde3993.png)

2022-12-14 09:56 UTC, ilija-lazoroski commented on monkey/monkey_island/cc/ui/src/components/ui-components/Error404Modal.js
> +              The server returned a 404 (NOT FOUND) response.
Can we add a custom message to this component and just rename it ErrorModal? We can probably reuse it in other place too.

2022-12-14 12:47 UTC, ilija-lazoroski approved these changes

2022-12-14 13:04 UTC, mssalvatore approved these changes

2022-12-14 13:05 UTC, merged