2950 custom sensitive text area widget
guardicore/monkey pull request #2973
Opened 2023-02-14 12:49 UTC by ilija-lazoroski

# What does this PR do?

Fixes #2950.
Things left to do:
* [ ] Test it with actual SHHKeypair
* [ ] Reduce duplication between `SensitiveTextInput` and `SensitiveTextareaInput`

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [x] If applicable, add screenshots or log transcripts of the feature working

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/15820737/218742840-9c6f4fb2-85ef-4bd9-8a04-77e8b18af837.png">
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/15820737/218742975-fd6f3f9f-4124-4e98-baaa-d3e133b9b0a8.png">

2023-02-14 16:07 UTC, VakarisZ requested changes
Let's not add more class components. Refactor monkey/monkey_island/cc/ui/src/components/ui-components/SensitiveTextareaInput.js to hooks

2023-02-14 16:18 UTC, cakekoa reviewed
Interesting solution -- I wonder how other password fields are implemented

2023-02-14 16:41 UTC, mssalvatore commented
Can we name this better?

![image](https://user-images.githubusercontent.com/19957806/218801149-a630379a-504b-4d7b-9286-6b2667322636.png)

2023-02-14 16:42 UTC, mssalvatore requested changes

2023-02-14 16:42 UTC, mssalvatore commented on CHANGELOG.md
> +- Fixed plaintext private key in SSHKey pair list in UI. #2950
This should NOT be in the v2.0.0 changelog.

2023-02-14 16:49 UTC, ilija-lazoroski commented
> Can we name this better?
> 
> ![image](https://user-images.githubusercontent.com/19957806/218801149-a630379a-504b-4d7b-9286-6b2667322636.png)

We can name it the same for every item there...

<img width="653" alt="image" src="https://user-images.githubusercontent.com/15820737/218803056-de98b404-5930-4a6a-9d24-58128d7f2d4b.png">

2023-02-14 17:25 UTC, cakekoa reviewed
Is there a way we can reduce code duplication between the two SensitiveText components?

2023-02-14 17:54 UTC, mssalvatore commented
@ilija-lazoroski 
> We can name it the same for every item there...
We can't name it "Key Pair 1", "Key Pair 2", ...?

2023-02-14 18:03 UTC, ilija-lazoroski commented
> @ilija-lazoroski 
> > We can name it the same for every item there...
> 
> We can't name it "Key Pair 1", "Key Pair 2", ...?

I didn't found any way to do it like that. Do we want to spend some time?

2023-02-14 18:20 UTC, mssalvatore commented
> Do we want to spend some time?

Nah. It's fine.

2023-02-14 18:46 UTC, cakekoa approved these changes

2023-02-15 08:28 UTC, shreyamalviya approved these changes

2023-02-15 12:24 UTC, merged