Redefine FingerprintData as pydantic model
guardicore/monkey pull request #2986
Opened 2023-02-17 11:52 UTC by shreyamalviya

# What does this PR do?

Fixes a part of #2136

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
    > No, the things breaking it will be fixed in other tasks of the issue.
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [ ] ~Have you successfully tested your changes locally? Elaborate:~
    > ~Tested by {Running the Monkey locally with relevant config/running Island/...}~
* [ ] ~If applicable, add screenshots or log transcripts of the feature working~

2023-02-17 12:26 UTC, mssalvatore requested changes

2023-02-17 12:26 UTC, mssalvatore commented on monkey/infection_monkey/dataclasses/fingerprint_data.py
> +    services: List[NetworkService] = Field(default=[])
```suggestion
    protocol: NetworkProtocol
    port: NetworkPort
    services: NetworkService
```

2023-02-17 13:21 UTC, mssalvatore commented on monkey/infection_monkey/dataclasses/fingerprint_data.py
> +    services: List[NetworkService] = Field(default=[])
Maybe we need

```python
FingeprintedPort
    protocol: NetworkProtocol
    port: NetworkPort
    services: NetworkService

class FingerprintData(InfectionMonkeyBaseModel):
    os_type: Optional[OperatingSystem]
    os_version: Optional[str]
    services: List[FingerPrintedPort]

2023-02-17 13:29 UTC, closed without merging

2023-02-20 08:30 UTC, ilija-lazoroski commented
Suppressed by #2987