SMB: Add SMBOptions to SMBPlugin
guardicore/monkey pull request #3089
Opened 2023-03-10 16:23 UTC by ilija-lazoroski

Issue: #2952

# What does this PR do?

Fixes part of #2952 

Add any further explanations here.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by unit tests
* [x] If applicable, add screenshots or log transcripts of the feature working

2023-03-10 16:55 UTC, mssalvatore commented
@ybasford Option descriptions could use your expert opinion.

2023-03-10 16:57 UTC, mssalvatore requested changes
Vulture fails

2023-03-10 16:57 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +        le=100.0,
These maximums seem somewhat arbitrary. Are they based on anything?

2023-03-13 08:10 UTC, shreyamalviya requested changes
Configuration options we need:
- target ports
- try all open ports

2023-03-13 08:15 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +    )
Yep, we don't but RPC transport has that option which we were hard-coding to `False`.

2023-03-13 08:16 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +    )
That probably make sense.

2023-03-13 09:02 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +    )
Exactly, we don't specifically handle cases where Kerberos is used. Do we need anything else for it to work or is our existing logic enough?

2023-03-13 11:10 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +    )
Probablyyyy. We need to check that.

2023-03-13 11:53 UTC, mssalvatore commented
>  We should consider adding the option of choosing both or one of port 445 and port 139 instead of hard-coding it to be both. Probably checkboxes.

@shreyamalviya We discussed it on Friday. The issue is that 445 and 139 aren't really the right configuration options. The right set of configuration options are checkboxes regarding whether or not we should use the protocol over NetBIOS (see https://www.upguard.com/blog/smb-port). After some discussion, we decided this requires the user to have more knowledge of SMB and its history than they probably want. We decided that, since it's so easy to modify and release new versions of the plugin, we could add this option at a later date if a user requests it. For now, we decided to just hard code both.

2023-03-13 11:54 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +        le=100.0,
Only if we add a note to the description that this could cause the agent to hang on shutdown.

2023-03-13 11:56 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +    )
Should these just be the same option?

2023-03-13 11:56 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +        le=100.0,
Then we should also change things in Hadoop

2023-03-13 11:57 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/smb/src/smb_options.py
> +    )
https://github.com/guardicore/monkey/pull/3089#discussion_r1133563064 Yep.

2023-03-13 12:27 UTC, shreyamalviya approved these changes

2023-03-13 12:28 UTC, merged