2952 smb exploiter implementation
guardicore/monkey pull request #3104
Opened 2023-03-13 19:59 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #2952. SMB exploiter

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-03-14 06:29 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/smb/src/plugin.py
> +        self._smb_exploiter = SMBExploiter(credentials, smb_exploit_client, smb_propagation_client)
Why are we passing `credentials` to both `SMBExploitClient` and `SMBExploiter`?

2023-03-14 07:55 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +# SMB
?

2023-03-14 07:57 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +    def exploit(self, host: TargetHost, options: SMBOptions) -> Optional[Tuple[str, Credentials]]:
This should be the only public method?

2023-03-14 07:59 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +        destination_path = get_agent_dst_path(host)
What's the point of trying to move the agent when brute force failed?

2023-03-14 08:17 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +                continue
Maybe it would be better to wrap the sequence with 
```
try:
    ....
except (SMBError): 
    continue
```

This `if not something: continue` is not a good pattern

2023-03-14 08:29 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +            return credentials
Could this be a separate method that tries to establish an smb connection to the host with given credentials? It should return the connection.

2023-03-14 08:30 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +        """File path if the agent was copied successfully, otherwise None"""
No a fan of these comments

2023-03-14 08:34 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +        return None
just return `destination`? Generally, I'm not too happy that half of the code in this file is checking if the previous statement was successful and returning None or continuing.

2023-03-14 08:35 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +    def query_shares(self, host: TargetHost, path: PurePath):
missing typehint

2023-03-14 08:39 UTC, VakarisZ commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +    def connected_shares(self, shares, host: TargetHost, credentials: Credentials):
add a type hint

2023-03-14 20:15 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/smb/src/smb_exploiter.py
> +        return None
I'm not sure if splitting this into two methods is valuable.

2023-03-14 20:16 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/smb/src/smb_exploiter.py
> +            return False
This is fine for SMB, but not necessarily generalizable for other brute force exploiters. Why not have `copy_file()` raise some kind of `RemoteFileCopyError` if copy fails?

2023-03-14 20:17 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/smb/src/smb_exploiter.py
> +            return False
Perhaps the client should just have `execute()`. There may be other commands we want to execute besides just the agent (see SSH exploiter)

2023-03-15 08:14 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/smb/src/smb_exploiter.py
> +            return False
We can address this comment in the next task of the issue.

2023-03-15 13:55 UTC, shreyamalviya requested changes

2023-03-15 13:55 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/smb/src/smb_utils.py
> +        )
Let's add keyword arguments so it's easier to read and maintain.

2023-03-15 13:55 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/smb/src/smb_exploiter.py
> +        credentials_list = generate_brute_force_credentials(credentials)
Let's not use "list" in the variable name.
```suggestion
        credential_combinations = generate_brute_force_credentials(credentials)
```

2023-03-15 14:09 UTC, mssalvatore requested changes
I think we need to think critically about the code quality of `SMBExploitClient`

- Some methods duplicate code
- smb_utils.py isn't necessary. These functions are only used in `SMBExploitClient`, and we should define things close to where they are used to maximize cohesion.
- A lot of these methods are pretty long.
- Lots of things are returning `None` when they could instead just raise exceptions

Basically, it looks like a lot of this was maybe copied out of the existing `SMBTools`, but we know code quality there is poor. This is an opportunity for us to write better code; let's not waste it.

2023-03-15 14:09 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/smb/src/smb_exploit_client.py
> +        return True
This duplicates a lot of code from `authenticate()`

2023-03-15 14:17 UTC, mssalvatore commented
If the focus of this PR is really about `SMBExploiter`, there are two things that leak out of `SMBExploitClient` that should be fixed.

1. Prefer raising exceptions to returning `None`
2. The `SMBExploiter` should be as general as possible. Passing parameters like `remote_path`, `destination_path`, and `credentials` into `SMBExploitClient` will prevent us from repurposing `SMBExploiter` as a brute-force [strategy](https://refactoring.guru/design-patterns/strategy). In summary, it seems like `SMBExploitClient` should be much more stateful than it is. Once I connect, it should maintain the necessary connection details so I don't need to reconnect for every SMB operation.

2023-03-17 13:16 UTC, mssalvatore requested changes

2023-03-17 13:16 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/i_remote_access_client.py
> +class IRemoteAccessClient(ABC):
These docstrings are all missing a summary/description.

2023-03-17 13:16 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +class BruteForceExploiter:
Missing docstrings

2023-03-17 13:16 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        propagation_credentials_repository: IPropagationCredentialsRepository,
This should just accept a callable that returns all credentials to try. We can provide a callable class in `tools/` that queries the repository and calls `generate_brute_force_credentials()` and construct an instance of it in `plugin.py`.

2023-03-17 13:16 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        destination = get_agent_dst_path(host)
This should also probably be passed into the constructor.

2023-03-17 13:16 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        raise Exception("Failed to copy file")
NIT: Double check the logic on this, but I think we can clean it up a tad:
```suggestion
    def _copy_file(
        self, file: BytesIO, destination: str, exploit_client: IRemoteAccessClient, interrupt: Event
    ) -> str:
        file_data = file.getvalue()
        with contextlib.suppress(RemoteFileCopyError):
            exploit_client.copy_file(file_data, destination)
            return destination

        other_destinations = exploit_client.get_available_paths()
        for other_destination in interruptible_iter(other_destinations, interrupt):
            with contextlib.suppress(RemoteFileCopyError):
                exploit_client.copy_file(file_data, other_destination)
                return other_destination


        raise Exception("Failed to copy file")
```

2023-03-17 14:33 UTC, cakekoa commented on monkey/infection_monkey/exploit/tools/i_remote_access_client.py
> +    def execute(self, command: str):
Hmm, how would the `BruteForceExploiter` decide which one to run? Or should we just do this in the `command` string that's passed to `execute()`?

2023-03-17 18:21 UTC, cakekoa commented on monkey/infection_monkey/exploit/tools/i_remote_access_client.py
> +    def execute(self, command: str):
So `execute_detached()` would be different from just running the dropper then?

2023-03-20 12:18 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/i_remote_access_client.py
> +    def execute(self, command: str):
Yes

2023-03-20 12:29 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        raise Exception("Failed to login with the given credentials")
This should be publishing `ExploitationEvents`

2023-03-20 12:30 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        exploit_client.execute(command)
This should be publishing `PropagationEvents`

2023-03-20 12:31 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        build_command: Callable[[str, str], str],
```suggestion
        build_command: Callable[[Path, Path], str],
```

2023-03-20 12:36 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        agent_binary = self._agent_binary_repository.get_agent_binary(host.operating_system)
Query OS and download the correct agent binary.

2023-03-20 12:36 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        command = self._build_command(str(file_path), str(self._destination_path))
Pass the OS to `self._build_command()` to build the command for the correct OS.

2023-03-20 12:41 UTC, mssalvatore commented on monkey/tests/unit_tests/infection_monkey/exploit/tools/test_brute_force_exploiter.py
> +    client.execute.return_value = True
Violates the `IRemoteAccessClient` interface

2023-03-20 16:51 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        tags: Set[str],
```suggestion
        event_tags: Set[str],
```

2023-03-20 16:52 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        tags: Set[str],
There should be a unit test that verifies all events are published with these tags

2023-03-20 16:52 UTC, mssalvatore commented on monkey/tests/unit_tests/infection_monkey/exploit/tools/test_brute_force_exploiter.py
> +#     assert not result.propagation_success
Remove?

2023-03-20 17:07 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        time: float = time(),
Don't set this default.

2023-03-20 17:07 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +                self._publish_exploitation_event(host, success=True, tags=self._tags.union(tags))
Timestamp needs to be collected before the event takes place.

2023-03-20 17:11 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        raise Exception("Failed to copy file")
Can we reduce duplication by just surfacing all errors up to the calling function? We can have the calling function pass the tags output parameter down to this one.

2023-03-20 17:12 UTC, mssalvatore commented on monkey/infection_monkey/exploit/tools/brute_force_exploiter.py
> +        raise Exception("Failed to copy file")
I didn't see a unit test that verifies only copy tags get added if copy fails.

2023-03-20 19:41 UTC, mssalvatore approved these changes

2023-03-20 19:47 UTC, merged