3150 log target host ip
guardicore/monkey pull request #3172
Opened 2023-03-29 09:34 UTC by ordabach

# What does this PR do?

Fixes #3150.

Instead of logging the whole TragetHost object, it logs only the host IP.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [x] Do all end-to-end tests pass?
* [x] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] ~If applicable, add screenshots or log transcripts of the feature working~

2023-03-29 10:08 UTC, VakarisZ requested changes
Missed some statements in:
`monkey/infection_monkey/exploit/mssqlexec.py:72`
`monkey/infection_monkey/exploit/mssqlexec.py:88`
`puppet/puppet.py:88`
A bunch of in:
`monkey/infection_monkey/exploit/sshexec.py`
A bunch in:
`monkey/infection_monkey/exploit/wmiexec.py`
`monkey/infection_monkey/exploit/zerologon.py`

I'm mainly worried about failing exploiters (pretty common) spamming the logs with the same kind of information (open services didn't change based on exploiter, so it doesn't make sense to log them for each host)

2023-03-29 12:15 UTC, mssalvatore approved these changes

2023-03-29 12:16 UTC, mssalvatore requested changes
@ordabach Flake8 and Black fail. Do you have pre-commit hooks installed?

2023-03-29 13:41 UTC, VakarisZ commented on monkey/infection_monkey/exploit/mssqlexec.py
> +            "aborting brute force".format(host.ip, port)
`host` is already an IP... this is what happens when people neglect good naming conventions

2023-03-30 09:19 UTC, VakarisZ approved these changes

2023-03-30 11:52 UTC, ilija-lazoroski approved these changes
All good with testing, just squash the commits with the same message.

2023-03-30 13:08 UTC, merged