Fix missing fields in configuration page
guardicore/monkey pull request #3215
Opened 2023-04-10 13:50 UTC by shreyamalviya

# What does this PR do?

Fixes #3031 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [ ] ~Have you checked that you haven't introduced any duplicate code?~

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Do all unit tests pass?
* [ ] ~Do all end-to-end tests pass?~
* [x] Any other testing performed?
    > Tested UI
* [x] If applicable, add screenshots or log transcripts of the feature working
    > Check [this](https://github.com/guardicore/monkey/pull/3215#issuecomment-1503144668)

2023-04-10 14:47 UTC, mssalvatore requested changes
I'm really not a fan of this approach. "warning_box_scan_my_networks" is not configurable, and should therefore not be a field in the configuration.

Is it possible to add metadata to the field that we can interpret in the frontend? `Field()` accepts kwargs as `**extra` that will be included in the schema (see https://github.com/pydantic/pydantic/blob/d3cd6c39b4ee617116ff7bb7aab58dcd832d8401/pydantic/fields.py#L222-L301).

The UI could support "warning_message" or "info_message" and render the box appropriate box above the field.

If it's not possible, I'd rather leave these boxes out than add configuration options that aren't really configurable.

2023-04-11 06:50 UTC, shreyamalviya commented
I suppose we could override the original widgets to display a message (whose level (info/warning) could be decided dynamically) with the input field but again, lots of duplication for different types of inputs and more room for bugs. I think this is an acceptable solution, though. I'll try it out.

2023-04-11 11:44 UTC, mssalvatore commented on monkey/common/agent_configuration/agent_sub_configurations.py
> +        configuration_message=(
Why not have this field called "warning_message". We could also support "info_message". This would allow a field to provide one or both.

2023-04-11 12:25 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/configuration-components/CheckboxWithMessage.js
> +    }
Does it make sense to put `InfoBox.js` and `WarningBox.js` back and just have these `if` statements create InfoBox and WarningBox components?

2023-04-11 12:29 UTC, mssalvatore approved these changes

2023-04-11 13:12 UTC, merged