3167 UI credentials collectors
guardicore/monkey pull request #3258
Opened 2023-04-26 16:04 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #3167 .

Things left to do:
- [ ] Unit tests for `CredentialsCollectorConfiguration`
- [ ] Fix BB test configurations that adds credentials collectors

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [x] Do all unit tests pass?
* [x] Do all end-to-end tests pass?
* [x] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [x] If applicable, add screenshots or log transcripts of the feature working

https://user-images.githubusercontent.com/15820737/234634593-98dd0bb5-1366-49d0-8d0e-06942ba3375b.mov

2023-04-26 16:17 UTC, mssalvatore commented on monkey/common/agent_configuration/agent_configuration.py
> +    credentials_collectors: Optional[CredentialsCollectorsConfiguration] = Field(
Make this match `ExploitationConfiguration.exploiters`. It shouldn't be optional and we don't need to define a separate configuration.

2023-04-27 06:23 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/configuration-components/FormConfig.tsx
> +export const EXPLOITERS_CONFIG_PATH = 'propagation.' + EXPLOITERS_PATH_PROPAGATION;
Are these constants needed here? Let's move them to where they're relevant.

2023-04-27 08:26 UTC, ilija-lazoroski commented on monkey/monkey_island/cc/ui/src/components/configuration-components/FormConfig.tsx
> +export const EXPLOITERS_CONFIG_PATH = 'propagation.' + EXPLOITERS_PATH_PROPAGATION;
Probably just a leftover. I will re/move them as needed. Thanks!

2023-04-27 09:56 UTC, shreyamalviya requested changes

2023-04-27 09:56 UTC, shreyamalviya commented on monkey/common/agent_configuration/agent_configuration.py
> +        " cause crashes of the local machine/system.",
```suggestion
        description="Click on a credentials collectors to get more information"
        " about it. \n \u26A0 Note that using unsafe options may"
        " result in unexpected behavior on the machine.",
```

2023-04-27 09:56 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/configuration-components/FormConfig.tsx
> +  }
```suggestion
    if (path !== selectedSection) {
      let newSchema = _.cloneDeep(formUiSchema);
      _.set(newSchema, path, uiSubschema);
      setFormUiSchema(newSchema);
    } else {
      setFormUiSchema(uiSubschema);
    }
  }
```

2023-04-27 09:56 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/configuration-components/FormConfig.tsx
> +  </div>)
Is this function necessary? Just do:
```suggestion
return (
    <Form {...props}
          uiSchema={formUiSchema}
          formContext={{'selectedPlugins': selectedPlugins,
                        'setSelectedPlugins': setSelectedPlugins,
                        'setUiSchema': setUiSchemaForCurrentSection,
                        'section': selectedSection
                      }}>
      <button type='submit' className={'hidden'}>Submit</button>
    </Form>
  )
```

2023-04-27 09:56 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
> +
This is inconsistent. If we have constants for the exploiters configuration path in the file relevant to them, we should have them for credential collectors too.

2023-04-27 09:56 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +const CREDENTIALS_COLLECTORS_CONFIG_PATH = 'credentials_collectors';
This is related to the above comment. Move this constant to the relevant file and import it like we've done for exploiters.

2023-04-27 09:56 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/utils/SafeOptionValidator.js
> +      selectedPlugins: Object.keys(config.credentials_collectors)
If we change the configuration path of something, we'll need to update to here as well as `PluginSelectorTemplate.tsx`.

I see that the way we access the configuration is different in both places, but we should have the paths at one place and create a utility method that accepts the path as a parameter which we can use in this file. Maybe in a different PR.

2023-04-27 11:24 UTC, mssalvatore approved these changes

2023-04-27 11:43 UTC, shreyamalviya approved these changes

2023-04-27 11:52 UTC, merged