3242 masquerade tab UI
guardicore/monkey pull request #3301
Opened 2023-05-04 15:34 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #3242 .

Add any further explanations here.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [x] Do all end-to-end tests pass?
* [x] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [x] If applicable, add screenshots or log transcripts of the feature working

<img width="834" alt="image" src="https://user-images.githubusercontent.com/15820737/236403855-b0322006-6ad5-4adf-af23-736526f050da.png">

2023-05-04 18:47 UTC, mssalvatore requested changes

2023-05-04 18:47 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +      'description': 'List of masque strings that will be appended to the agent binaries '
Don't say "appended". Anywhere. This is an implementation detail. Neither the user, the UI, or the API care at all about the specific implementation details and how this data is added to the binary.

2023-05-04 18:47 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +      'title': 'Masque list',
```suggestion
      'title': 'Strings',
```

2023-05-04 18:47 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +  updateMasqueList = () => {
```suggestion
  updateMasqueStrings = () => {
```

2023-05-04 18:47 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +      masqueList: {},
```suggestion
      masqueStrings: {},
```

2023-05-05 05:29 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +      'description': 'List of masque strings that will be appended to the agent binaries '
I think we could be more descriptive about what this feature does and why it's added.

2023-05-05 06:37 UTC, shreyamalviya requested changes

2023-05-05 06:37 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +    'masque_linux_strings': {
```suggestion
    'linux_masque_strings': {
```
For Windows as well

2023-05-05 07:07 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +  'This feature can be particularly helpful when testing custom detection rules.',
"Infection Monkey can emulate malware by injecting custom data into Agent binaries. This feature can be particularly helpful when testing custom detection rules."

The rest should be in the documentation, where features are explained better.

2023-05-05 07:08 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +      'description': 'List of masque strings that will be insert to the Linux Agent binaries '
```suggestion
      'description': 'List of masque strings that will be applied to the Linux Agent binary'
```
We've used "apply" everywhere in the backend. Let's stick to one.
Same for Windows.

2023-05-05 07:56 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +      'description': 'A masque string that will be applied to the Linux Agent binaries.'
```suggestion
      'description': 'A masque string that will be applied to the Linux Agent binary.'
```

2023-05-05 08:21 UTC, shreyamalviya approved these changes
LGTM, but we should talk about whether we want to change the backend to accept a list of masques or put that off right now, before merging.

2023-05-05 08:27 UTC, ilija-lazoroski commented
After a discussion, we decided to move on to what the endpoints return which is a single masque. If needed, the change for a list of masques in the UI won't affect the whole feature implementation.

2023-05-05 08:34 UTC, merged