UI: Submit masquerade fields
guardicore/monkey pull request #3307
Opened 2023-05-05 10:57 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #3242 .

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-05-05 14:21 UTC, mssalvatore requested changes

2023-05-05 14:21 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx
> +  put(endpoint: string, contents: any, refreshToken: boolean = false, type: string = 'JSON'): Promise<Response> {
We should just have `put()` and `put_json()`

2023-05-05 14:21 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +  sendLinuxMasqueStrings() {
We'll need to add prefixes that allow the UI to tell the difference between strings and arbitrary bytes.

2023-05-05 14:21 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +  }
Can we extract a function, pass in an API Endpiont and a specific variable from the state, and reduce duplication?

2023-05-05 14:21 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +  getNullTerminatedBytesFromStrings = (stringsArray) => {
```suggestion
  transformStringsToBytes = (stringsArray) => {
```

2023-05-08 11:57 UTC, mssalvatore approved these changes

2023-05-08 12:15 UTC, mssalvatore commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +
see https://github.com/guardicore/monkey/pull/3316#discussion_r1187360304

2023-05-08 12:21 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +    return stringsArray.filter(str => str !== '');
This is duplicated in #3316.

2023-05-08 12:24 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +  }
Also duplicated in #3316

2023-05-08 12:26 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +    return stringsArray.filter(str => str !== '');
Oh, alright. Be careful that nothing's lost when you rebase.

2023-05-08 12:50 UTC, merged