SNMP: Implement SNMP exploit client
guardicore/monkey pull request #3323
Opened 2023-05-08 19:53 UTC by cakekoa

# What does this PR do?

Fixes part of #3234.
Merge after #3313

Implements the SNMP exploit client

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-05-08 19:56 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/snmp_exploit_client.py
> +        # - nsExtendOutLine
❤️

2023-05-10 15:19 UTC, mssalvatore requested changes

2023-05-10 15:19 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/snmp_exploit_client.py
> +COMMAND_NAME = "command0"
It might be a good idea to randomize this.
1. "command0" is pretty generic. We could risk overwriting an existing command that the user wants to be there.
2. If multiple agents attack the same machine simultaneously, they could interfere with eachother.

2023-05-10 15:19 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/snmp_command_builder.py
> +    return f'-c "{command}"'
Should the "-c" just be added to `SNMP_LINUX_COMMAND_TEMPLATE`?

2023-05-10 15:19 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/snmp_exploit_client.py
> +            self._clear_command(host.ip, COMMAND_NAME, community_string)
We need to make sure we "clear command" even if execute fails.

2023-05-10 18:36 UTC, cakekoa commented on monkey/agent_plugins/exploiters/snmp/src/snmp_command_builder.py
> +    return f'-c "{command}"'
My reasoning was that it was a nice clear way to show that the command needed to be quoted.

This is going to be reworked as we work to shrink the commands to fit the 255 character limit imposed by the MIB

2023-05-10 18:39 UTC, cakekoa commented on monkey/agent_plugins/exploiters/snmp/src/snmp_command_builder.py
> +    return f'-c "{command}"'
Note: We also need to be sure to run the wget command in silent mode. We will probably have to silence the agent's output as well

2023-05-11 16:08 UTC, mssalvatore requested changes

2023-05-11 16:08 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/plugin.py
>          except Exception as err:
This return should explicitly set exploitation and propagation success.

2023-05-11 16:08 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/plugin.py
> +        exploit_client = SNMPExploitClient(agent_id, agent_event_publisher, plugin_name)
I don't see where SNMPExploitClient is using `plugin_name`

2023-05-11 16:08 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/plugin.py
> +        exploit_client = SNMPExploitClient(agent_id, agent_event_publisher, plugin_name)
Doesn't SNMPExploitClient require SNMPClient?

2023-05-11 16:08 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/snmp_exploit_client.py
> +            raise err
This is a noop. I think you can just `try/finally`.

```suggestion
```

2023-05-11 16:08 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/snmp_exploit_client.py
> +            raise err
This is a noop. I think you can just `try/finally`.

```suggestion
```

2023-05-11 16:08 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/snmp_client.py
> +                ObjectIdentity("NET-SNMP-EXTEND-MIB", "nsExtendStatus", f'"{command_name}"'),
NIT: Consider a constant for the MIB name. It could help avoid typos.

2023-05-11 16:16 UTC, cakekoa commented on monkey/agent_plugins/exploiters/snmp/src/plugin.py
> +        exploit_client = SNMPExploitClient(agent_id, agent_event_publisher, plugin_name)
It's using it for the propagation/exploitation events (it's called `exploiter_name` in the class)

2023-05-11 16:26 UTC, cakekoa commented on monkey/agent_plugins/exploiters/snmp/src/plugin.py
> +        exploit_client = SNMPExploitClient(agent_id, agent_event_publisher, plugin_name)
It has a default argument. I'll just remove the default argument and inject it. We'll want to use the SNMPClient anyways to implement should_attempt_exploit()

2023-05-11 17:20 UTC, mssalvatore approved these changes

2023-05-11 17:29 UTC, merged