3234 options
guardicore/monkey pull request #3324
Opened 2023-05-08 20:56 UTC by cakekoa

# What does this PR do?

Fixes part of #3234.
Merge after #3323.

Adds options for SNMP exploiter

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-05-10 10:52 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/snmp/config-schema.json
> +            "description": "The maximum time (in seconds) to wait for a successfully exploited SNMP client to download the agent binary.",
```suggestion
            "description": "The maximum time (in seconds) to wait for a successfully exploited SNMP client to download the Agent binary.",
```

2023-05-10 16:01 UTC, mssalvatore requested changes

2023-05-10 16:01 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/snmp/src/community_string_generator.py
> +) -> Iterable[str]:
There's no reason to couple this function to `IPropagationCredentialsRepository`. We can modify the code that calls this to pass in credential and then also drop the changes to the unit tests.

2023-05-11 18:49 UTC, mssalvatore approved these changes

2023-05-11 18:50 UTC, mssalvatore commented
Merged in a5ec39e071570eb119310b9a39551cf8c8d1f1e8

2023-05-11 18:50 UTC, closed without merging