3243 arbitrary bytes
guardicore/monkey pull request #3332
Opened 2023-05-14 20:39 UTC by ordabach

# What does this PR do?

Fixes #`put issue number here`.

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-05-15 06:52 UTC, ilija-lazoroski requested changes
We have just two commits, one with a temp message. Not really enough for these changes.

2023-05-15 13:59 UTC, mssalvatore requested changes
If the masque is set via the API directly, instead of via the UI as an intermediary, the UI will not display the bytes set by the API, because the API caller will not be aware of the prefixes that the UI uses to distinguish strings from base64. **If the UI receives a masque without the requisite prefixes, it should assume all data is "arbitrary" and display is as base64..** 

I'm not we need a list of base64 strings. The idea here was to keep the UI simpler. The user needs to be able to specify a list of strings so they don't need to worry about string termination (null characters). For base 64, we really just need one text area that the user can paste arbitrary data into.

2023-05-15 14:51 UTC, ilija-lazoroski commented on monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> +          description: 'List of masque strings that will be applied to the Linux Agent binary.'
Here we have `List of masque strings` and the title is `Texts`. I think we should be consistent with the terminology everywhere.

2023-05-16 14:54 UTC, mssalvatore approved these changes

2023-05-16 14:55 UTC, merged