3171 exploit client
guardicore/monkey pull request #3361
Opened 2023-05-19 15:58 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #3171 .

Address the ports TODO.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-05-22 08:19 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            return False, ""
```suggestion
            return False, "Exploitation was unsuccessful, did not attempt propagation"
```

2023-05-22 08:19 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            if agent_binary_downloaded.is_set():
Where is this being set?

2023-05-22 08:19 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +        )
Not in this PR, but these could be moved to exploit tools as well.

2023-05-22 08:31 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            if agent_binary_downloaded.is_set():
This comes from the HTTP server. More precisely `agent_binary_http_serveri.bytes_downloaded`. `is_set` tells us whether the agent binary was fully downloaded.

2023-05-22 08:55 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +        )
Probably for #3314 .

2023-05-22 09:02 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            ports_to_try.update(relevant_tcp_ports_on_host)
Option name doesn't match with the behavior. This is also trying ports whose services are unknown.

2023-05-22 10:58 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            ports_to_try.update(relevant_tcp_ports_on_host)
I also don't think not trying unknown service ports is a good idea. Maybe we should change the option name or add another one?

2023-05-22 11:04 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            ports_to_try.update(relevant_tcp_ports_on_host)
Let's just add text to the configuration option mentioning that ports with unknown services will also be tried.

2023-05-22 11:32 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/config-schema.json
> +            "description": "Attempt the exploiter on all TCP ports discovered from network scanning which have MSSQL running. Ports with unknown services will also be included.",
@ybasford any suggestions?

2023-05-22 13:53 UTC, mssalvatore requested changes

2023-05-22 13:53 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/config-schema.json
> +            "description": "Attempt the exploiter on all TCP ports discovered from network scanning which have MSSQL running. Ports with unknown services will also be included.",
I think we should break this option up. 1 option for trying any known MSSQL ports. A separate option for trying UNKNOWN ports.

2023-05-22 13:54 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            pass
```suggestion
```

2023-05-22 13:56 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            pass
Maybe you mean ?
```suggestion
        return (False, False)
```

2023-05-22 14:03 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +        self._publish_propagation_event(host, timestamp, propagation_success, propagation_message)
Why are these events using the same timestamp? They're separate events that took place at separate times.

Rather than returning sucess/message from exploit() and propagate(), what if those methods just published their own events?

2023-05-22 14:28 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_client.py
> +                logger.debug("MSSQL connection is not active")
How does the caller know whether or not login was successful?

2023-05-22 14:32 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/mssql/src/mssql_client.py
> +                logger.debug("MSSQL connection is not active")
`SELECT 1` is just a small query that returns 1 if we were able to connect to the mssql server. We check what the server returns using `fetchall`

2023-05-22 21:57 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/mssql/config-schema.json
> +            "description": "Attempt the exploiter on all TCP ports discovered from network scanning in which the service using the port is unknown.",
```suggestion
        "try_discovered_unknown_service_ports": {
            "title": "Try discovered unknown service ports",
            "description": "Attempt the exploiter on all TCP ports discovered from network scanning in which the service using the port is unknown.",
```

2023-05-23 11:13 UTC, mssalvatore commented
There's still a commit in the history with a "TEMP" prefix.

2023-05-23 11:40 UTC, mssalvatore requested changes
Unit tests fail.

Run coverage to make sure no tests are missing.

2023-05-23 11:40 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_client.py
> +        raise RuntimeError("Failed to MSSQL server with provided credentials")
```suggestion
        raise RuntimeError("Failed to authenticate with the MSSQL server with provided credentials")
```

2023-05-23 11:40 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_client.py
> +            raise RuntimeError("Failed to execute the command") from err
I may be wrong, but this won't allow the caller to see the actual error message unless they view the stack trace. This could make debugging difficult.

2023-05-23 11:40 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +        return exploitation_success, propagation_success
Try to keep all part so of a method at the same level of abstraction. Consider adding A `self._exploit() -> bool` that handles login and publishing of exploitation events, the same way `self._propagate()` does.

2023-05-23 11:40 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploit_client.py
> +            if agent_binary_downloaded.is_set():
NIT

Alternatively:

```suggestion
            if agent_binary_downloaded.wait(agent_binary_download_timeout):
```

2023-05-23 11:40 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploiter.py
> +        ports_to_try: Set[NetworkPort],
Try to keep type hints as open as possible. [Postel's Law (the robustness principle)](https://en.wikipedia.org/wiki/Robustness_principle) states "Be conservative in what you do, be liberal in what you accept from others." 

What does this component actually need?
```suggestion
        ports_to_try: Iterable[NetworkPort],
```

2023-05-23 11:40 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/plugin.py
> +        ports_to_try.update(unknown_tcp_ports)
NIT:

Alternatively:
```suggestion
    services_to_scan = {}
    if options.try_discovered_mssql_ports:
        services_to_scan.add(NetworkService.MSSQL)
        
    if options.try_discovered_unknown_ports:
        services_to_scan.add(NetworkService.UNKNOWN)
    
    additional_ports = {
        p for p in tcp_ports.open if tcp_ports[p].service in services_to_scan
    }
    ports_to_try.update(additional_ports)
```

2023-05-23 13:44 UTC, cakekoa commented on monkey/agent_plugins/exploiters/mssql/src/mssql_client.py
> +            raise RuntimeError("Failed to execute the command") from err
I wasn't aware of [this feature](https://docs.python.org/3/tutorial/errors.html#exception-chaining) until copilot suggested it. It's basically the same as not having the `from` clause, but modifies the output to say that the error was directly caused by another error

2023-05-23 15:08 UTC, mssalvatore approved these changes

2023-05-23 15:23 UTC, merged