3165 powershell exploit client
guardicore/monkey pull request #3375
Opened 2023-05-23 13:39 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #3165 .

Add any further explanations here.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-05-23 15:27 UTC, cakekoa requested changes

2023-05-23 15:27 UTC, cakekoa commented on monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_auth_options.py
> +def test_get_auth_options__auth_type_with_password(http_only_host):
The above also applies to the auth_type tests

2023-05-23 17:06 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/powershell/src/powershell_auth_options.py
> +AUTH_NTLM = "ntlm"
Consider an Enum for this.

2023-05-23 17:06 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/powershell/src/powershell_auth_options.py
> +ENCRYPTION_NEVER = "never"
Consider an Enum for this.

2023-05-23 17:07 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/powershell/src/powershell_client.py
> +    def connect_with_user(
"connect_with_user" sounds like an outreach program. "connect" or "login" are probably more succint.

2023-05-23 17:10 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/powershell/src/powershell_auth_options.py
> +ENCRYPTION_NEVER = "never"
If nothing else needs these constants, an Enum may be overkill.

2023-05-23 17:10 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/powershell/src/powershell_auth_options.py
> +AUTH_NTLM = "ntlm"
If nothing else needs these constants, an Enum may be overkill.

2023-05-23 17:15 UTC, mssalvatore requested changes
`is_windows_os()` is deprecated (plugin.py). Use `get_os()` instead.

2023-05-24 10:32 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
> +        return OperatingSystem.WINDOWS
?

2023-05-24 10:35 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
> +        return OperatingSystem.WINDOWS
Check `IRemoteAccessClient`

2023-05-24 11:16 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
> +        return OperatingSystem.WINDOWS
I don't think it's meant to be used in the command builder.

2023-05-24 11:17 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
> +        return OperatingSystem.WINDOWS
https://github.com/guardicore/monkey/pull/3375/files#diff-d1b3fcdac5d1861ab5f5fc98129f518d758777a419380e3f1ac49895499c8302R83

2023-05-24 11:19 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
> +        return OperatingSystem.WINDOWS
Someone else has done that I guess..

2023-05-24 11:42 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
> +        return OperatingSystem.WINDOWS
I don't think there's any problem using it in the command builder. PowerShell does run on Linux, we just don't support it (yet). There's a foreseeable future where using `get_os()` to build the command makes sense. For now, it doesn't make much of a difference.

2023-05-24 12:17 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
> +        return OperatingSystem.WINDOWS
Leaving this as it is.
We've done it the same way in the other exploiters too. It makes sense since we're calling it inside the client at which point we know the remote OS is Windows.

2023-05-24 15:08 UTC, cakekoa commented on monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_remote_access_client.py
> +    mock_powershell_client.copy_file.return_value = True
```suggestion
```

2023-05-24 17:01 UTC, closed without merging