Migrate LDAPExploitServer from processes to threads
guardicore/monkey pull request #3439
Opened 2023-06-23 11:36 UTC by shreyamalviya

# What does this PR do?

Fixes a part of #3388 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Do all unit tests pass?
* [ ] ~Do all end-to-end tests pass?~
* [ ] Any other testing performed?
    > Tested by running Log4Shell (logstash on linux, solr on windows)
* [ ] ~If applicable, add screenshots or log transcripts of the feature working~

2023-06-23 11:50 UTC, mssalvatore commented on monkey/infection_monkey/exploit/log4shell_utils/ldap_server.py
> +            self._server_thread.join(timeout)
There's a logical change here. The old code would send a signal to twisted (via SIGTERM) to shutdown. This code doesn't make any attempt to signal twisted to stop.

2023-06-23 16:19 UTC, mssalvatore commented on monkey/infection_monkey/exploit/log4shell_utils/ldap_server.py
> +        from twisted.internet import reactor
Perhaps this should be wrapped in a reusable function called `import_twisted_reactor()` that can be called from `_run_twisted_reactor()` as well.

2023-06-26 05:33 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/log4shell_utils/ldap_server.py
> +        from twisted.internet import reactor
It [doesn't seem easy to do that with a decorator](https://stackoverflow.com/questions/29018731/python-import-module-from-decorator).

2023-06-26 05:50 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/log4shell_utils/ldap_server.py
> +        from twisted.internet import reactor
We can't do that because the import is only available in that function's scope then.

2023-06-26 11:52 UTC, mssalvatore commented on monkey/infection_monkey/exploit/log4shell_utils/ldap_server.py
> +        from twisted.internet import reactor
Fair enough.

2023-06-26 11:55 UTC, mssalvatore requested changes
I think the reason that `from twisted.internet import reactor` is buried down in a bunch of different functions was because there were issues importing it from different threads. Since LDAPServer is only now imported within its own process, we may be able to just import it once at the top like any other import. It's worth a quick test.

2023-06-26 12:57 UTC, mssalvatore commented
```
08:50:29 [CRITICAL] _legacy.publishToNewObserver.147: Unhandled Error
Traceback (most recent call last):
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/base.py", line 501, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/defer.py", line 532, in addCallback
    return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/defer.py", line 512, in addCallbacks
    self._runCallbacks()
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
--- <exception caught here> ---
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/base.py", line 513, in _continueFiring
    callable(*args, **kwargs)
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/base.py", line 1314, in _reallyStartRunning
    self._handleSignals()
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/posixbase.py", line 142, in _handleSignals
    _SignalReactorMixin._handleSignals(self)
  File "/home/msalvatore/venvs/monkey/lib/python3.11/site-packages/twisted/internet/base.py", line 1281, in _handleSignals
    signal.signal(signal.SIGINT, reactorBaseSelf.sigInt)
  File "/usr/lib/python3.11/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
builtins.ValueError: signal only works in main thread of the main interpreter
```

Looks like twisted doesn't like if you start it in a thread. The simplest options for us are:

1. See if we can instruct twisted not to register a signal handler
2. Catch and suppress this exception as long as it doesn't result in any functional impact for us.

2023-06-26 16:39 UTC, merged