Implement Log4ShellExploiter
guardicore/monkey pull request #3442
Opened 2023-06-26 14:08 UTC by shreyamalviya

# What does this PR do?

Fixes #`put issue number here`.

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-06-30 11:39 UTC, mssalvatore requested changes
Unit tests fail due to a circular import.

2023-06-30 11:46 UTC, mssalvatore requested changes
```
monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploiter.py:49:5: C901 'Log4ShellExploiter.exploit_host' is too complex (11)
    def exploit_host(
    ^
1     C901 'Log4ShellExploiter.exploit_host' is too complex (11)
```

Are you running your pre-commit hooks?

2023-06-30 12:10 UTC, shreyamalviya commented
> Unit tests fail due to a circular import

This'll go away once the exploit client is in place. I made temporary changes to verify that the tests pass.

> Are you running your pre-commit hooks?

Yes, I plan on getting to that.

2023-07-03 06:48 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploiter.py
> +        logger.exception("An unexpected error occurred while stopping the HTTP server")
Use `SERVER_SHUTDOWN_TIMEOUT`.

2023-07-03 13:05 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_utils/service_exploiters/logstash.py
> +from infection_monkey.exploit.log4shell_utils.service_exploiters import IServiceExploiter
We need to import this from the plugin itself

2023-07-03 13:06 UTC, mssalvatore requested changes
We should get rid of the `log4shell_utils` subdirectory. That was useful when everything was crammed together in `infection_monkey/exploits`, but since the plugin is now isolated, there's no clear differentiator between what belogs in `log4shell_utils` and what belongs at the top level. The distinction is meaningless.

2023-07-04 12:23 UTC, merged