3388 log4shell exploit client
guardicore/monkey pull request #3448
Opened 2023-06-29 12:09 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #3388 

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-06-30 06:46 UTC, shreyamalviya requested changes

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        for service_exploit in get_log4shell_service_exploiters():
```suggestion
        for service_exploiter in get_log4shell_service_exploiters():
```

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +
If an exception occurs, you're logging and sending an exploitation event twice, each with different messages, for the same activity. Once here, and once on line 74.

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        return exploitation_success, propagation_success
The logic is flawed here. This function will always return the last values of these variables. What if a service was exploited successfully before that?

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +            exploitation_message = "" if exploitation_success else f"Failed to exploit via {url}"
Add the URL to the exploitation message even if it was successful.

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +            exploitation_message = "" if exploitation_success else f"Failed to exploit via {url}"
On second thought, we should get rid of the `url` argument in this function. It's already being logged in the exploiter before this is called.

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +            self._publish_exploitation_event(target_host, timestamp, True)
We shouldn't be publishing an exploitation event in a function that's meant for propagation.

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +            self._publish_exploitation_event(target_host, timestamp, True)
Move the exploitation event logic out of here and into `_run_exploit()`, before this function is called.

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        sleep(VICTIM_WAIT_SLEEP_TIME_SEC)
We don't need this if we're using events. This was present in the old logic because we were using a timer. The `wait()` function in the new logic takes care of that.

2023-06-30 06:46 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        sleep(VICTIM_WAIT_SLEEP_TIME_SEC)
Same as above

2023-06-30 11:41 UTC, mssalvatore requested changes
Unittests fail
```
FAILED tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py::test_exploit_host__success_returned_on_ldap_server_stop_fail[OperatingSystem.WINDOWS] - AttributeError: 'NoneType' object has no attribute 'stop'
FAILED tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py::test_exploit_host__success_returned_on_ldap_server_stop_fail[OperatingSystem.LINUX] - AttributeError: 'NoneType' object has no attribute 'stop'
```

2023-07-03 06:28 UTC, shreyamalviya requested changes

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +                    break
```suggestion
                if propagation_success:
                    break
```

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +            logger.exception("An exception was encountered while attempting to exploit Log4Shell")
By this logic, if one of the service exploiters throws an exception, none of the ones after that will be attempted.

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +    def _assess_exploit_status(
This is a misleading name. It isn't just _assessing_, it's also carrying out a part of the exploitation.

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +    def _assess_exploitation(
Same as above

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +    def _assess_propagation(
Same as above

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        self._publish_propagation_event(target_host, success=propagation_success)
Where's the failure propagation event being published?

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        return event.is_set()
The `EggTimer` logic is pointless here.
```suggestion
        if event.wait(timeout):
                return True
                
        return False
```

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        return event.is_set()
Could also just do:
```suggestion
        return event.wait(timeout)
```

2023-07-03 06:28 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        return event.is_set()
https://docs.python.org/3/library/threading.html#threading.Event.wait

2023-07-03 07:55 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        return event.is_set()
Nope we couldn't. In this way we wait for a fraction but no more then the timeout. This way we are more responsive and safe. For example what if we wait for the timeout and the event happens afterwards?

2023-07-03 07:57 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        self._publish_propagation_event(target_host, success=propagation_success)
Right there on line 157.

2023-07-03 08:18 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        return event.is_set()
> For example what if we wait for the timeout and the event happens afterwards?

I don't understand what you mean.

2023-07-03 08:20 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
> +        return event.is_set()
Never mind. We're doing this because of the interrupt.

2023-07-03 12:26 UTC, mssalvatore approved these changes
This will get a final review in #3442

2023-07-03 12:31 UTC, merged