3410 http agent binary server
guardicore/monkey pull request #3492
Opened 2023-07-12 17:21 UTC by cakekoa

# What does this PR do?

Fixes part of #3410.

Adds the HTTPAgentBinaryServer

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-07-12 18:37 UTC, mssalvatore requested changes

2023-07-12 18:37 UTC, mssalvatore commented on monkey/infection_monkey/exploit/http_agent_binary_server.py
> +        Unregister an Agent binary from being served
```suggestion
        Deregister an Agent binary from being served
```

2023-07-12 19:11 UTC, mssalvatore commented
We'll need to fix the commits that start with `TEMP`.

2023-07-12 19:59 UTC, cakekoa commented on monkey/infection_monkey/exploit/agent_binary_request.py
> +class AgentBinaryRequest:
Hmm... Download... Chit? Receipt? Ticket? Token? Registration?

2023-07-13 11:55 UTC, mssalvatore commented on monkey/infection_monkey/exploit/agent_binary_request.py
> +class AgentBinaryRequest:
Record? Resource?

This one is hard.

2023-07-13 12:43 UTC, mssalvatore commented on monkey/infection_monkey/exploit/agent_binary_request.py
> +    bytes_downloaded: Event
Suggestion:
```suggestion
    download_completed: Event
```

2023-07-13 12:51 UTC, mssalvatore commented on monkey/infection_monkey/exploit/agent_binary_request.py
> +class AgentBinaryRequest:
After discussion, we've decided to produce two dataclasses. The one that gets returned to the user will be `AgentBinaryDownloadTicket` and the one stored internally in the handler is `AgentBinaryDownloadReservation`.

2023-07-17 17:23 UTC, cakekoa commented
This works, but comes with a caveat: Since the `HTTPAgentBinaryServer` is run in a separate process and plugins are loaded dynamically, the `HTTPAgentBinaryServer` will have trouble with an `AgentBinaryTransform` that is defined by the plugin, since it won't know how to look it up in order to serialize it

2023-07-18 07:21 UTC, shreyamalviya reviewed
Nice job!

2023-07-19 13:10 UTC, shreyamalviya commented on monkey/infection_monkey/exploit/http_agent_binary_server.py
> +        :param agent_binary_transform: A function that transforms the Agent binary before serving.
I have a vague idea right now that this has something to do with the dropper script, but can we make this more descriptive? Someone reading this for the first time can't make much of it.

2023-07-19 14:16 UTC, ilija-lazoroski approved these changes

2023-07-19 14:27 UTC, merged