3425 rdp domain logic
guardicore/monkey pull request #3562
Opened 2023-08-07 20:55 UTC by cakekoa

# What does this PR do?

Fixes part of #3425.

Considers local domains when generating credentials.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-08-08 08:40 UTC, shreyamalviya requested changes

2023-08-08 08:40 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +    credentials: Sequence[Credentials], domains: Sequence[str], running_from_windows: bool
"from" or "on"? Let's pick one.
```suggestion
    credentials: Sequence[Credentials], domains: Sequence[str], running_on_windows: bool
```

2023-08-08 08:40 UTC, shreyamalviya commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +def _get_domain() -> str:
These functions could use better names.
```suggestion
def _get_local_machine_domain() -> str:
```

2023-08-08 09:48 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +    credentials: Sequence[Credentials], domains: Sequence[str], running_from_windows: bool
I think we have "from" in Powershell. The purpose is the same so I say lets go with consistency.

2023-08-08 11:25 UTC, mssalvatore requested changes

2023-08-08 11:25 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +    credentials: Sequence[Credentials], domains: Sequence[str], running_from_windows: bool
Then it needs to be fixed in `plugin.py`, which has `running_on_windows`.

2023-08-08 11:25 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +def _get_domains(running_from_windows: bool) -> Set[str]:
```suggestion
def _get_local_domains(running_from_windows: bool) -> Set[str]:
```

2023-08-08 11:25 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +    domains = {"."}
Does this work with aardwolf?

2023-08-08 12:08 UTC, cakekoa commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +    domains = {"."}
I'm wondering the same thing

2023-08-09 09:39 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py
> +    domains = {"."}
It works!
<img width="1519" alt="image" src="https://github.com/guardicore/monkey/assets/15820737/869a1ebd-8604-4876-afc0-31c5a931030a">

2023-08-09 09:47 UTC, ilija-lazoroski commented
From rdp-64 to rdp-65. Intentionally added the wrong credentials to see every domain tried.
```
2023-08-09 09:44:38,749 [4896:ExploiterThread-02:DEBUG] rdp_client._connect.65: Connecting with user: WORKGROUP\m0nk3y
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,812 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,828 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,828 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,828 [4896:ExploiterThread-02:ERROR] rdp_client._connect.68: Error connecting: CredSSP - Server sent an error! Code: 0xc000006d
NoneType: None
2023-08-09 09:44:38,828 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to all_events_topic
2023-08-09 09:44:38,828 [3864:PluginEventForwarder:DEBUG] agent_event_forwarder.send_event.46: Adding event of type ExploitationEvent to the queue to send to the Island
2023-08-09 09:44:38,828 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to ExploitationEvent-type
2023-08-09 09:44:38,828 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to rdp-exploiter-tag
2023-08-09 09:44:38,828 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to attack-t1110-tag
2023-08-09 09:44:38,828 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to attack-t1021-tag
2023-08-09 09:44:38,828 [4896:ExploiterThread-02:DEBUG] rdp_client._connect.65: Connecting with user: RDP-64\m0nk3y
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,843 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,859 [4896:ExploiterThread-02:ERROR] rdp_client._connect.68: Error connecting: CredSSP - Server sent an error! Code: 0xc000006d
NoneType: None
2023-08-09 09:44:38,859 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to all_events_topic
2023-08-09 09:44:38,859 [3864:PluginEventForwarder:DEBUG] agent_event_forwarder.send_event.46: Adding event of type ExploitationEvent to the queue to send to the Island
2023-08-09 09:44:38,859 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to ExploitationEvent-type
2023-08-09 09:44:38,859 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to rdp-exploiter-tag
2023-08-09 09:44:38,859 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to attack-t1110-tag
2023-08-09 09:44:38,859 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to attack-t1021-tag
2023-08-09 09:44:38,859 [4896:ExploiterThread-02:DEBUG] rdp_client._connect.65: Connecting with user: .\m0nk3y
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,874 [4896:ExploiterThread-02:ERROR] rdp_client._connect.68: Error connecting: CredSSP - Server sent an error! Code: 0xc000006d
NoneType: None
2023-08-09 09:44:38,874 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to all_events_topic
2023-08-09 09:44:38,874 [3864:PluginEventForwarder:DEBUG] agent_event_forwarder.send_event.46: Adding event of type ExploitationEvent to the queue to send to the Island
2023-08-09 09:44:38,874 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to ExploitationEvent-type
2023-08-09 09:44:38,874 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to rdp-exploiter-tag
2023-08-09 09:44:38,874 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to attack-t1110-tag
2023-08-09 09:44:38,874 [3864:PluginEventForwarder:DEBUG] pypubsub_agent_event_queue._publish_event.55: Publishing a ExploitationEvent event to attack-t1021-tag
2023-08-09 09:44:38,890 [4896:ExploiterThread-02:DEBUG] rdp_client._connect.65: Connecting with user: WORKGROUP\m0nk3y
2023-08-09 09:44:38,906 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.32: hashlib using "pure" for "md4"
2023-08-09 09:44:38,953 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,953 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,953 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,953 [4896:ExploiterThread-02:DEBUG] hmac.hmacselector.42: hmac using "builtin" for "md5"
2023-08-09 09:44:38,953 [4896:ExploiterThread-02:DEBUG] hashlib.hashselector.37: hashlib using "builtin" for "md5"
2023- [...]

2023-08-09 11:19 UTC, mssalvatore approved these changes

2023-08-09 11:19 UTC, mssalvatore commented on monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_credentials_generator.py
> +    print(generated_credentials)
```suggestion
```

2023-08-09 11:20 UTC, mssalvatore requested changes

2023-08-09 11:20 UTC, mssalvatore commented on monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_credentials_generator.py
> +def patch_win32api_get_user_name(local_user):
Missing type hints.

2023-08-09 11:20 UTC, mssalvatore commented on monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_credentials_generator.py
> +def local_user():
Missing type hints.

2023-08-09 12:07 UTC, mssalvatore approved these changes

2023-08-09 12:09 UTC, merged