3543 wmi hanging
guardicore/monkey pull request #3588
Opened 2023-08-15 14:59 UTC by ilija-lazoroski

# What does this PR do?

Fixes #`put issue number here`.

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-08-15 15:33 UTC, mssalvatore requested changes

2023-08-15 15:33 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/wmi/config-schema.json
> +            "maximum": 100.0
I don't think the user needs access to this. It's also confusing: The user may not know why any SMB settings are required on a WMI module.

2023-08-15 15:33 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/wmi/src/wmi_client.py
> +        # DCOMConnection.PINGTIMER = Timer(timeout, DCOMConnection.pingServer)
We may just need to live with this. #3557 will prevent the agent from hanging during shutdown. We can create an issue and pursue a resolution at a later date if it's a priority. I think the only real effect, here, is that the WMI exploiter will cause propagation to be very slow in some environments.

2023-08-15 15:33 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client.py
> +            self._wmi_client.login(self._host, credentials, self._options.smb_connect_timeout)
Is switching this order intentional?

2023-08-16 08:15 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client.py
> +            self._wmi_client.login(self._host, credentials, self._options.smb_connect_timeout)
Yep, I saw everywhere they were doing it like this. So I thought maybe it matters but nope. I will get it back to the original order

2023-08-16 16:45 UTC, mssalvatore approved these changes

2023-08-16 16:47 UTC, merged