Changed text to align with Readme formatting
guardicore/monkey pull request #3595
Opened 2023-08-20 11:37 UTC by ybasford

# What does this PR do?

Fixes #`put issue number here`.

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2023-08-21 13:40 UTC, mssalvatore requested changes

2023-08-21 13:40 UTC, mssalvatore commented on docs/content/setup/_index.md
> +After setting the Monkey up, check out our [Getting started guide](doc:getting-started).
Similarly, this link doesn't work in our development platform, which is problematic for us. Is there a specific tool we should be using to render the markdown during development?

2023-08-21 13:40 UTC, mssalvatore commented on docs/content/setup/aws.md
> +# Deployment
This change makes `Deployment` appear to be the same size as the title.

2023-11-01 12:28 UTC, ilija-lazoroski commented
@ybasford can we rebase this on develop ?

2024-01-02 12:28 UTC, mssalvatore commented
Happy New Year! This PR hasn't seen any activity since August. I'm closing this due to inactivity. We can reopen if this effort gets revived.

2024-01-02 12:28 UTC, closed without merging