Ransomware: Adds Change Wallpaper feature -  Fix Issue 1247
guardicore/monkey pull request #3861
Opened 2023-11-09 16:50 UTC by Brazilian2019

# What does this PR do?

Fixes #`1247`.

Changes the Windows Wallpaper to more accurately simulate ransomware attacks

## PR Checklist
* [X] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [X] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [X] Added relevant unit tests?
* [X] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [X] Any other testing performed?
    > Tested by Running the Monkey locally with relevant config
* [X] If applicable, add screenshots or log transcripts of the feature working
![PR1247](https://github.com/guardicore/monkey/assets/58901722/a87a6d0e-db97-4038-bbbc-b55b1f8b9fb7)

2023-11-09 16:55 UTC, mssalvatore reviewed
All we're missing is documentation.

2023-11-09 19:46 UTC, cakekoa commented on monkey/agent_plugins/payloads/ransomware/ransomware_wallpaper_no_text.png
What is the purpose of this file? Is it simply the original background in case we want to generate new overlay text?

2023-11-09 20:11 UTC, cakekoa reviewed
Should we also add a tag for [T1491](https://attack.mitre.org/techniques/T1491/)? We'd probably want to create a separate `DefacementEvent` for that though, so perhaps it should be a separate issue.

2023-11-10 08:10 UTC, VakarisZ commented on monkey/agent_plugins/payloads/ransomware/ransomware_wallpaper_no_text.png
3MB is a lot for that. Also, I'm not sure what the licensing are for these AI generated images

2023-11-10 12:53 UTC, mssalvatore commented on monkey/agent_plugins/payloads/ransomware/ransomware_wallpaper_no_text.png
> What is the purpose of this file? Is it simply the original background in case we want to generate new overlay text?

Correct, its there so we can change the text in the future.

> 3MB is a lot for that.

When Ransomware gets moved to its own repo, this will go with it, though it will always be in the history. If you want to come up with a solution that would allow us to put it on ice until we break out the repo but not forget to include it later, that would be fine.

> I'm not sure what the licensing are for these AI generated images

From OpenAI:

>Subject to the Content Policy and Terms, you own the images you create with DALL·E, including the right to reprint, sell, and merchandise – regardless of whether an image was generated through a free or paid credit.

https://help.openai.com/en/articles/6425277-can-i-sell-images-i-create-with-dall-e

2023-11-10 12:55 UTC, mssalvatore requested changes
@cakekoa 
> Should we also add a tag for [T1491](https://attack.mitre.org/techniques/T1491/)? We'd probably want to create a separate `DefacementEvent` for that though, so perhaps it should be a separate issue.

We already have `DefacementEvent`. But you're right, we should publish it with the correct attack tag.

2023-11-10 13:36 UTC, VakarisZ commented on monkey/agent_plugins/payloads/ransomware/ransomware_wallpaper_no_text.png
> Correct, its there so we can change the text in the future.

We should have asset storage somewhere locally or upload it to the S3. I've deleted the image from the codebase as in most cases it's not needed but adds 3MB's of size.

2023-11-10 13:50 UTC, mssalvatore commented on monkey/agent_plugins/payloads/ransomware/ransomware_wallpaper_no_text.png
The removal must be done via a rebase and modifying the commit that adds it. Otherwise the file will still be in the repository. I'll take care of it.

2023-11-10 13:52 UTC, mssalvatore commented on monkey/agent_plugins/payloads/ransomware/ransomware_wallpaper_no_text.png
Removed and force pushed.

2023-11-10 14:12 UTC, ilija-lazoroski commented on monkey/agent_plugins/payloads/ransomware/src/wallpaper_changer.py
> +        if is_windows_os():
Use `get_os` instead.

2023-11-10 15:14 UTC, mssalvatore approved these changes

2023-11-10 15:45 UTC, merged