3942 fix invalid credentials msg UI
guardicore/monkey pull request #3973
Opened 2023-12-21 15:41 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #3942 .

Any suggestion about fixing the logic is much appreciated.

Sorting is disabled but I will try to do that as well after we merge this PR.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [x] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [x] If applicable, add screenshots or log transcripts of the feature working

![image](https://github.com/guardicore/monkey/assets/15820737/6fa9afea-cd56-40a3-a43e-379bf57713b7)

2023-12-21 16:49 UTC, VakarisZ commented
I'm seeing things like: 
![image](https://github.com/guardicore/monkey/assets/36815064/04681ebe-f949-4b7f-a164-22782195dcc0)

But anyway, I think these error messages could pretty much just be the contents without the index. The actual solution is dynamic validation. We can discuss what we want to do during the release planning, I've made issues https://github.com/guardicore/monkey/issues/3974 and https://github.com/guardicore/monkey/issues/3975

2023-12-22 08:27 UTC, ilija-lazoroski commented
> I'm seeing things like: ![image](https://private-user-images.githubusercontent.com/36815064/292255674-04681ebe-f949-4b7f-a164-22782195dcc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzM3OTMsIm5iZiI6MTcwMzIzMzQ5MywicGF0aCI6Ii8zNjgxNTA2NC8yOTIyNTU2NzQtMDQ2ODFlYmUtZjk0OS00YjdmLWExNjQtMjI3ODIxOTVkY2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA4MjQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MzVmNGQ0ODUxMjEyNDZiMGIxMzdlY2Y0NDgxZDE4OTc5NzEwYTUzMjg3N2EyMGFhZTlhM2M4MjEyOGQyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7Z48wkIG9em15jFTL6Aeq87DaVT0XYNbsGslrt70r0)
> 
> But anyway, I think these error messages could pretty much just be the contents without the index. The actual solution is dynamic validation. We can discuss what we want to do during the release planning, I've made issues #3974 and #3975

For the above message, you need to sync your island dependencies.

2023-12-22 11:42 UTC, shreyamalviya requested changes

2023-12-22 11:42 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +        formCredentialsIsland[stateCredentials.id] = formatCredentialsForIsland([stateCredentials]);
Didn't we agree on modifying and only calling this function once per row, and storing that data to reuse here?

2023-12-22 11:42 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +    let formCredentialsIsland = {};
What does this object contain exactly? The name isn't very helpful.

2023-12-22 11:42 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +                  errorsId[credentialsId].push(indexes[0]);
Why are you only pushing `indexes[0]` to the array?

2023-12-22 11:42 UTC, shreyamalviya commented on monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> +                  return `Credentials Row #${actualRowIndex}: ${error.message.split(', ').pop()}`;
```suggestion
                  return `Row #${actualRowIndex}: ${error.message.split(', ').pop()}`;
```

2023-12-22 13:15 UTC, closed without merging