Rework all command builders from exploiters
guardicore/monkey pull request #4085
Opened 2024-02-19 17:58 UTC by ilija-lazoroski

# What does this PR do?

Fixes part of #4042.

Draft because I need reviews before starting other exploiters.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2024-02-19 18:32 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
> +    agent_command_builder.build_run_command(run_options)  # type: ignore
Specify the specific error code being ignored instead of blindly ignoring all errors.

Example:  `# type: ignore [arg-type]`

2024-02-19 18:32 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
> +    return agent_command_builder.get_command()
There's a lot of extra type hinting and type ignoring in here all to prevent duplication of the last 3 lines. I would recommend the following:

```python
def build_hadoop_command(...) -> str:
    if target_host.operating_system in [
        OperatingSystem.WINDOWS,
        None,  # if unknown OS, default to Windows (based on
        # https://www.shodan.io/search/facet?query=hadoop&facet=os)
    ]:
        return _build_windows_hadoop_command(...)

    return _build_linux_hadoop_command(...)

2024-02-20 13:10 UTC, mssalvatore requested changes

2024-02-20 13:10 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploiter.py
> +        agent_command_builder_factory: IAgentCommandBuilderFactory,
Does this component need to be coupled to the factory?

2024-02-20 13:10 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_command_builder.py
> +    command = agent_command_builder.get_command()
Both of these functions should reset the command builder before they build anything. As written, these two function are temporally coupled, but there's no reason that the run command must be built after the download command. If a developer changes the order these are called in the future it will introduce bugs.

2024-02-20 13:11 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
> +    return agent_command_builder.get_command()
Do these two functions need to be coupled to the factory?

2024-02-20 13:25 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploiter.py
> +        agent_command_builder_factory: IAgentCommandBuilderFactory,
Probably not. Since this is targeting just one OS we can create the command builder and pass it to this component or `exploit_host`. Let's choose one.

2024-02-20 13:27 UTC, ilija-lazoroski commented on monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
> +    return agent_command_builder.get_command()
We can pass the concrete builders but I don't see a point why would we do that.

2024-02-21 20:31 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/mssql/src/mssql_exploiter.py
> +        agent_command_builder_factory: IAgentCommandBuilderFactory,
Minimize coupling. Components should depend on only what they need.

2024-02-21 20:31 UTC, mssalvatore commented on monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
> +    return agent_command_builder.get_command()
Minimize coupling. Components should depend on only what they need.

2024-02-21 20:50 UTC, cakekoa commented on monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_command_builder.py
> +    expected_dropper_path: Optional[PureWindowsPath],
Unused parameter

2024-02-21 20:50 UTC, cakekoa commented on monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_command_builder.py
> +    expected_dropper_path: Optional[PureWindowsPath],
Unused parameter

2024-02-21 23:37 UTC, merged