Monkey tutorial
guardicore/monkey pull request #4175
Opened 2024-05-13 12:31 UTC by cakekoa

# What does this PR do?

Issue #`put issue number here`.

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

2024-05-13 13:35 UTC, shreyamalviya commented on docs/content/tutorials/hello-monkey.md
> +Before the Monkey can do anything useful, it needs to be configured. Otherwise, it won't know what exploits to attempt, or what machine(s) to attempt to breach.
```suggestion
Before the Monkey can do anything useful, it needs to be configured. Otherwise, it won't know which exploits to attempt, or which machine(s) to attempt to breach.

We'll need to configure Infection Monkey to exploit the vulnerable container. Select "Configure Monkey" on the "Getting Started" page (or select _Configuration_ in the navigation sidebar).

```

2024-05-13 13:35 UTC, shreyamalviya commented on docs/content/tutorials/hello-monkey.md
> +#### Tell the Monkey what machines to target
```suggestion
#### Tell the Monkey which machines to target
```

2024-05-13 13:35 UTC, shreyamalviya commented on docs/content/tutorials/hello-monkey.md
> +In our case, we know that the target machine has the hostname `hello`. In order to tell the Monkey to target that hostname, starting from the **Configuration** page, ensure that **Propagation** tab i
```suggestion
In our case, we know that the target machine has the hostname `hello`. In order to tell the Monkey to target that hostname, starting from the **Configuration** page, ensure that the **Propagation** tab is selected, and then select the **Network analysis** subtab. Then, under the "Scan target list" section, click the "+" button to add a target to scan. Enter our target hostname, `hello`, into the input field. Finally, make sure to scroll to the bottom and click **Submit** in order to save the configuration.
```

2024-05-13 13:35 UTC, shreyamalviya commented on docs/content/tutorials/hello-monkey.md
> +{{% /notice %}}
I don't think this needs to be a separate note. We can just add it to the paragraph above.

2024-05-13 13:35 UTC, shreyamalviya commented on docs/content/tutorials/hello-monkey.md
> +Great, the Monkey knows what machine to target. What happens if we run it? Select **1. Run Monkey** in the navigation sidebar to bring up the Run Monkey page. We'll choose the **From Island** option,
```suggestion
Great, the Monkey now knows which machine to target. What happens if we run it? Select **1. Run Monkey** in the navigation sidebar to bring up the Run Monkey page. We'll choose the **From Island** option, which will start the attack simulation from the Island machine. Go ahead and do that now.
```

2024-05-13 13:35 UTC, shreyamalviya commented on docs/content/tutorials/hello-monkey.md
> +Select **2. Infection Map** in the navigation sidebar. This brings up a network view (from the Monkey's perspective). You should notice and arrow appear between the `monkey-island` machine and the vu
```suggestion
You can also see the Monkey's progress by selecting **2. Infection Map** in the navigation sidebar. This brings up a network view (from the Monkey's perspective). You should see an arrow appear between the `monkey-island` machine and the vulnerable container. If you look at the legend, you'll notice that this indicates that the Monkey scanned the container.
```

2024-05-13 13:35 UTC, shreyamalviya commented on docs/content/tutorials/hello-monkey.md
> +#### Tell the Monkey what exploiters to use
```suggestion
#### Tell the Monkey which exploiters to use
```

2024-05-13 14:37 UTC, VakarisZ commented on docs/content/tutorials/hello-monkey.md
> +In this tutorial, we will use the Infection Monkey to exploit a simple vulnerability. We will configure Infection Monkey to exploit the vulnerability, and then run the Monkey to observe that it is ab
Let's be more respectful: "Hello, fellow primate!"

2024-05-13 14:40 UTC, VakarisZ commented on docs/content/tutorials/hello-monkey.md
> +The Infection Monkey will only attempt to breach the machines that you've explicitly configured it to target. This helps to ensure that the Monkey doesn't run amok on your network.
What is "amok"?

2024-05-13 14:51 UTC, VakarisZ commented on docs/content/tutorials/hello-monkey.md
> +The Infection Monkey will only attempt to breach the machines that you've explicitly configured it to target. This helps to ensure that the Monkey doesn't run amok on your network.
we probably don't need this note. It should be properly explained in the config description. If such a basic/fundamental concept needs a note then we're doing something wrong

2024-05-13 14:55 UTC, VakarisZ commented on docs/content/tutorials/hello-monkey.md
> +The Infection Monkey will only attempt to breach the machines that you've explicitly configured it to target. This helps to ensure that the Monkey doesn't run amok on your network.
Either way, it's better to explain this in "What happened" section rather than trying to pre-emptively jump to the results

2024-05-13 16:31 UTC, cakekoa commented on docs/content/tutorials/hello-monkey.md
> +In this tutorial, we will use the Infection Monkey to exploit a simple vulnerability. We will configure Infection Monkey to exploit the vulnerability, and then run the Monkey to observe that it is ab
Lol -- well it's the name I gave to this tutorial. Since it's redundant with the title that Hugo adds to the page, maybe I should just remove it

2024-05-13 16:52 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +The Infection Monkey will only attempt to breach the machines that you've explicitly configured it to target. This helps to ensure that the Monkey doesn't run amok on your network.
![image](https://github.com/guardicore/monkey/assets/19957806/75dce9ee-b44a-42a6-8c57-3dfdd11411db)
https://www.merriam-webster.com/dictionary/amok

2024-05-13 17:09 UTC, mssalvatore requested changes

2024-05-13 17:09 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +![Getting started page](../../images/tutorials/hello-monkey/2-getting-started-page.jpg)
```suggestion
![Infection Monkey login screen](../../images/tutorials/hello-monkey/1-registration-page.jpg)

After registering, you'll be automatically logged in. You'll be brought to the welcome screen, which looks like this:

![Getting started page](../../images/tutorials/hello-monkey/2-getting-started-page.jpg)
```

2024-05-13 17:09 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +The Infection Monkey will only attempt to breach the machines that you've explicitly configured it to target. This helps to ensure that the Monkey doesn't run amok on your network.
> If such a basic/fundamental concept needs a note then we're doing something wrong

The target audience is someone who's not at all familiar with infection Monkey. I think this note is worthwhile.

2024-05-13 17:09 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +You can also see the Monkey's progress by selecting **2. Infection Map** in the navigation sidebar. This brings up a network view (from the Monkey's perspective). You should see an arrow appear betwe
```suggestion
You can see the Monkey's progress by selecting **2. Infection Map** in the navigation sidebar. This brings up a network view (from the Monkey's perspective). You should see an arrow appear between the `monkey-island` machine and the vulnerable container. If you look at the legend, you'll notice that this indicates that the Monkey scanned the container.
```

2024-05-13 17:09 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +Now we're going to configure the Monkey to use an exploiter. In order to do that, select **Configuration** in the navigation sidebar. Select the **Propagation** tab, and the **Exploiters** subtab. Yo
```suggestion
Now we're going to configure the Monkey to use an exploiter. In order to do that, select **Configuration** in the navigation sidebar. Select the **Propagation** tab, and the **Exploiters** subtab. You should see a list of _Enabled exploiters_ which, you'll notice, is empty. This is because we haven't installed any exploiters yet. Thankfully, the _Enabled exploiters_ list provides a link to a page where we can download exploiters, so let's follow that link and install an exploiter.
```

2024-05-13 17:09 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +Now we're going to configure the Monkey to use an exploiter. In order to do that, select **Configuration** in the navigation sidebar. Select the **Propagation** tab, and the **Exploiters** subtab. Yo
```suggestion
Now we're going to configure the Monkey to use an exploiter. In order to do that, select **Configuration** in the navigation sidebar. Select the **Propagation** tab, and the **Exploiters** subtab. You should see a list of _Enabled exploiters_, which you'll notice, is empty. This is because we haven't installed any exploiters yet. Thankfully, the _Enabled exploiters_ list provides a link to a page where we can download and install exploiter plugins, so let's follow that link and install an exploiter.
```

2024-05-13 17:09 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +Enter `user` into the **Identity** field, and `j688yq/pB{5=` in the **Password** field, and hit the _Save_ button.
Is there any reason not to use a simpler, more human-readable password?

2024-05-13 17:11 UTC, mssalvatore commented on docs/content/tutorials/hello-monkey.md
> +In this tutorial, we will use the Infection Monkey to exploit a simple vulnerability. We will configure Infection Monkey to exploit the vulnerability, and then run the Monkey to observe that it is ab
It should be "Hello, Monkey" (if we keep it).

2024-05-13 19:21 UTC, cakekoa commented on docs/content/tutorials/hello-monkey.md
> +Enter `user` into the **Identity** field, and `j688yq/pB{5=` in the **Password** field, and hit the _Save_ button.
I suppose not

2024-05-14 08:34 UTC, VakarisZ commented on docs/content/tutorials/hello-monkey.md
> +The Infection Monkey will only attempt to breach the machines that you've explicitly configured it to target. This helps to ensure that the Monkey doesn't run amok on your network.
I really don't understand the reason for this note when the next section is called "Tell the Monkey which machines to target"

2024-05-14 10:01 UTC, VakarisZ commented
I have slimmed down the tutorial to make it more about the subject and less about explaining how our UI components work. You can take inspiration or clean it up: https://github.com/guardicore/monkey/commit/b6b0a26dbfce84dfc9b61587c8814e830ed13702

2024-05-14 15:50 UTC, cakekoa commented
The docker compose script references a specific build of the Island docker image because the current version on docker hub does not have the MONGO_URL fix. The referenced build is not on docker hub.

2024-05-14 18:57 UTC, merged