Typescript support implemented
guardicore/monkey pull request #888
Opened 2020-11-23 15:04 UTC by VakarisZ

# What does this PR do? 

Implements typescript, which adds readability and reliability.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?

## Testing Checklist

* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by building dist and running.

2020-11-23 15:05 UTC, VakarisZ commented on monkey/monkey_island/cc/ui/package.json
> +    "react-step-wizard": "^5.3.5",
This does not belong here, but will be used shortly in scenarios

2020-11-25 22:08 UTC, acepace commented on monkey/monkey_island/cc/ui/package.json
> +    "@types/node": "^14.14.9",
Shouldn't be a runtime dependency

2020-11-25 22:08 UTC, acepace commented on monkey/monkey_island/cc/ui/tsconfig.json
> +    "target": "es5",
Why so low?

2020-11-28 19:30 UTC, acepace commented on monkey/monkey_island/cc/ui/package.json
> +    "snyk": "^1.427.0",
Shoudln't be a prod dependency

2020-11-28 19:31 UTC, acepace commented on monkey/monkey_island/cc/ui/package.json
> +    "ts-loader": "^8.0.11",
Should not be a prod dependency

2020-11-28 19:31 UTC, acepace commented on monkey/monkey_island/cc/ui/package.json
> +    "typescript": "^4.1.2"
Should not be a prod dependency

2020-11-28 19:32 UTC, acepace requested changes
Note this means that all the current run scripts that just run the existing files will fail if they are TS files.

2020-12-09 08:15 UTC, VakarisZ commented on monkey/monkey_island/cc/ui/tsconfig.json
> +    "target": "es5",
Upped to es6

2021-04-13 14:02 UTC, VakarisZ commented on monkey/monkey_island/cc/ui/package.json
> +    "react-step-wizard": "^5.3.5",
Removed

2021-04-14 07:04 UTC, VakarisZ commented on monkey/monkey_island/cc/ui/tsconfig.json
> +    "target": "es6",
![image](https://user-images.githubusercontent.com/36815064/114667916-bceed500-9d08-11eb-9aa6-85d2280d15ee.png)

Not low, this is recommended.

2021-04-14 13:59 UTC, mssalvatore approved these changes
TBH, I have basically no experience with typescript and very limited experience with React and Node. If you addressed @acepace's comments (which it looks to me like you did), then I'm happy with this PR.

2021-04-15 09:43 UTC, merged