Update aws.md
guardicore/monkey pull request #934
Opened 2021-01-22 15:14 UTC by MarketingYeti

copyedits

# What does this PR do? 

Fixes #`put issue number here`. 

Add any further explanations here. 

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...} 
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

2021-01-22 15:20 UTC, MarketingYeti commented on docs/content/setup/aws.md
> +1. Choose an EC2 instance type with at least 1GB of RAM for optimal performance or stick with the default reccomendation.
recommendation

2021-01-25 16:55 UTC, mssalvatore requested changes

2021-01-25 16:55 UTC, mssalvatore commented on docs/content/setup/aws.md
> +Currently, there's no "upgrade-in-place" option when a new version comes out. To get an updated version, you can deploy a new machine from the marketplace. If you'd like to keep your existing configu
"when a new version is released."

2021-01-27 16:42 UTC, mssalvatore approved these changes

2021-01-27 16:42 UTC, merged